// Vitest global setup — runs once before the entire test suite.
// Builds and starts the Docker image from the repo root, then tears it down
// after all tests complete.
// Set MM_SKIP_DOCKER=1 to skip Docker management and use a running instance.

import { execFileSync } from 'child_process';
import * as path from 'path';
import { fileURLToPath } from 'url';

const mmUrl = process.env.MM_URL ?? 'https://local.motion-master.synapticon.com:8443';
const CONTAINER_NAME = 'motion-master-api-test';
const IMAGE_NAME = 'motion-master';

// Self-signed cert generated by the container entrypoint — skip TLS verification.
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

let containerStarted = false;

async function waitForApi(timeoutMs = 60_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`${mmUrl}/api/version`);
      if (res.ok) {
        return;
      }
    } catch {}
    await new Promise((r) => setTimeout(r, 1_000));
  }
  throw new Error(`Motion Master not reachable at ${mmUrl} after ${timeoutMs}ms`);
}

export async function setup() {
  if (process.env.MM_SKIP_DOCKER === '1') {
    await waitForApi();
    return;
  }

  const srcDir = fileURLToPath(new URL('.', import.meta.url));
  const repoRoot = path.resolve(srcDir, '../../..');

  // Remove any leftover container from a previous failed run.
  execFileSync('docker', ['rm', '-f', CONTAINER_NAME], { stdio: 'ignore' });

  console.log('[global-setup] Building Docker image…');
  execFileSync('docker', ['build', '-t', IMAGE_NAME, repoRoot], { stdio: 'inherit' });

  console.log('[global-setup] Starting container…');
  execFileSync(
    'docker',
    ['run', '-d', '--rm', '--network', 'host', '--name', CONTAINER_NAME, IMAGE_NAME],
    { stdio: 'inherit' },
  );
  containerStarted = true;

  console.log('[global-setup] Waiting for API…');
  await waitForApi();
}

export async function teardown() {
  if (containerStarted) {
    console.log('[global-setup] Stopping container…');
    execFileSync('docker', ['stop', CONTAINER_NAME], { stdio: 'inherit' });
  }
}
