// Generated by `motion-master generate-object-addresses` from somanet-v5.6.6.xml — do not edit.
// Regenerating is a two-step job: run that command, then `tools/format.sh` — clang-format
// wraps the declarations that overrun 100 columns, and it does so context-sensitively
// enough that reproducing its choices here would be guesswork.
//
// CiA 402 drive profile (0x6xxx) — 181 addresses.
//
// Each constant carries an object's index, subindex and the C++ type its declared
// ETG.1020 type maps to, so a call site cannot disagree with the object it names:
//
//     device.value(objects::kStatusword)        // std::optional<uint16_t>
//     device.readValue(objects::kDeviceName)    // std::expected<std::string, ...>
//
// The union of every device in the ESI is emitted: which module is fitted is unknowable
// offline, so an address that does not apply to the drive in front of you simply fails
// to resolve at runtime, exactly as a hand-written index would. The trailing comment on
// each line is the ESI's own name, access mode and unit — the unit especially, since a
// temperature in milli-degrees looks exactly like one in degrees until a motor stops.

#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "node/device_parameter.h"

namespace mm::node::cia402::objects {

/// Error code — ro
inline constexpr ObjectAddress<uint16_t> kErrorCode{0x603F, 0x00};

/// Controlword — rw
inline constexpr ObjectAddress<uint16_t> kControlword{0x6040, 0x00};

/// Statusword — ro
inline constexpr ObjectAddress<uint16_t> kStatusword{0x6041, 0x00};

/// Quick stop option code — rw
inline constexpr ObjectAddress<int16_t> kQuickStopOptionCode{0x605A, 0x00};

/// Modes of operation — rw
inline constexpr ObjectAddress<int8_t> kModesOfOperation{0x6060, 0x00};

/// Modes of operation display — ro
inline constexpr ObjectAddress<int8_t> kModesOfOperationDisplay{0x6061, 0x00};

/// Position demand value — ro, Inc
inline constexpr ObjectAddress<int32_t> kPositionDemandValue{0x6062, 0x00};

/// Position actual value — ro, Inc
inline constexpr ObjectAddress<int32_t> kPositionActualValue{0x6064, 0x00};

/// Following error window — rw, Inc
inline constexpr ObjectAddress<uint32_t> kFollowingErrorWindow{0x6065, 0x00};

/// Following error time out — rw, ms
inline constexpr ObjectAddress<uint16_t> kFollowingErrorTimeOut{0x6066, 0x00};

/// Position window — rw, Inc
inline constexpr ObjectAddress<uint32_t> kPositionWindow{0x6067, 0x00};

/// Position window time — rw, ms
inline constexpr ObjectAddress<uint16_t> kPositionWindowTime{0x6068, 0x00};

/// Velocity demand value — ro, rpm
inline constexpr ObjectAddress<int32_t> kVelocityDemandValue{0x606B, 0x00};

/// Velocity actual value — ro, rpm
inline constexpr ObjectAddress<int32_t> kVelocityActualValue{0x606C, 0x00};

/// Velocity window — rw, rpm
inline constexpr ObjectAddress<uint16_t> kVelocityWindow{0x606D, 0x00};

/// Velocity window time — rw, ms
inline constexpr ObjectAddress<uint16_t> kVelocityWindowTime{0x606E, 0x00};

/// Velocity threshold — rw, rpm
inline constexpr ObjectAddress<uint16_t> kVelocityThreshold{0x606F, 0x00};

/// Velocity threshold time — rw, ms
inline constexpr ObjectAddress<uint16_t> kVelocityThresholdTime{0x6070, 0x00};

/// Target Torque — rw
inline constexpr ObjectAddress<int16_t> kTargetTorque{0x6071, 0x00};

/// Max torque — rw
inline constexpr ObjectAddress<uint16_t> kMaxTorque{0x6072, 0x00};

/// Max current — rw
inline constexpr ObjectAddress<uint16_t> kMaxCurrent{0x6073, 0x00};

/// Torque demand — ro
inline constexpr ObjectAddress<int16_t> kTorqueDemand{0x6074, 0x00};

/// Motor rated current — rw, mA
inline constexpr ObjectAddress<uint32_t> kMotorRatedCurrent{0x6075, 0x00};

/// Motor rated torque — rw, mNm
inline constexpr ObjectAddress<uint32_t> kMotorRatedTorque{0x6076, 0x00};

/// Torque actual value — ro
inline constexpr ObjectAddress<int16_t> kTorqueActualValue{0x6077, 0x00};

/// DC link circuit voltage — ro, mV
inline constexpr ObjectAddress<uint32_t> kDCLinkCircuitVoltage{0x6079, 0x00};

/// Target position — rw, Inc
inline constexpr ObjectAddress<int32_t> kTargetPosition{0x607A, 0x00};

/// Position range limit / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kPositionRangeLimitCount{0x607B, 0x00};

/// Position range limit / SubIndex 001 — rw, Inc
inline constexpr ObjectAddress<int32_t> kPositionRangeLimitSubIndex001{0x607B, 0x01};

/// Position range limit / SubIndex 002 — rw, Inc
inline constexpr ObjectAddress<int32_t> kPositionRangeLimitSubIndex002{0x607B, 0x02};

/// Home offset — rw, Inc
inline constexpr ObjectAddress<int32_t> kHomeOffset{0x607C, 0x00};

/// Software position limit / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSoftwarePositionLimitCount{0x607D, 0x00};

/// Software position limit / SubIndex 001 — rw, Inc
inline constexpr ObjectAddress<int32_t> kSoftwarePositionLimitSubIndex001{0x607D, 0x01};

/// Software position limit / SubIndex 002 — rw, Inc
inline constexpr ObjectAddress<int32_t> kSoftwarePositionLimitSubIndex002{0x607D, 0x02};

/// Polarity — rw
inline constexpr ObjectAddress<uint8_t> kPolarity{0x607E, 0x00};

/// Max motor speed — rw, rpm
inline constexpr ObjectAddress<uint32_t> kMaxMotorSpeed{0x6080, 0x00};

/// Profile velocity — rw, rpm
inline constexpr ObjectAddress<uint32_t> kProfileVelocity{0x6081, 0x00};

/// Profile acceleration — rw, rpm/s
inline constexpr ObjectAddress<uint32_t> kProfileAcceleration{0x6083, 0x00};

/// Profile deceleration — rw, rpm/s
inline constexpr ObjectAddress<uint32_t> kProfileDeceleration{0x6084, 0x00};

/// Quick stop deceleration — rw, rpm/s
inline constexpr ObjectAddress<uint32_t> kQuickStopDeceleration{0x6085, 0x00};

/// Motion profile type — rw
inline constexpr ObjectAddress<int16_t> kMotionProfileType{0x6086, 0x00};

/// Torque slope — rw
inline constexpr ObjectAddress<uint32_t> kTorqueSlope{0x6087, 0x00};

/// Torque profile type — rw
inline constexpr ObjectAddress<int16_t> kTorqueProfileType{0x6088, 0x00};

/// Gear ratio / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGearRatioCount{0x6091, 0x00};

/// Gear ratio / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kGearRatioSubIndex001{0x6091, 0x01};

/// Gear ratio / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kGearRatioSubIndex002{0x6091, 0x02};

/// Feed constant / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kFeedConstantCount{0x6092, 0x00};

/// Feed constant / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kFeedConstantSubIndex001{0x6092, 0x01};

/// Feed constant / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kFeedConstantSubIndex002{0x6092, 0x02};

/// Homing method — rw
inline constexpr ObjectAddress<int8_t> kHomingMethod{0x6098, 0x00};

/// Homing speeds / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kHomingSpeedsCount{0x6099, 0x00};

/// Homing speeds / SubIndex 001 — rw, rpm
inline constexpr ObjectAddress<uint32_t> kHomingSpeedsSubIndex001{0x6099, 0x01};

/// Homing speeds / SubIndex 002 — rw, rpm
inline constexpr ObjectAddress<uint32_t> kHomingSpeedsSubIndex002{0x6099, 0x02};

/// Homing acceleration — rw, rpm/s
inline constexpr ObjectAddress<uint32_t> kHomingAcceleration{0x609A, 0x00};

/// SI unit velocity — rw
inline constexpr ObjectAddress<uint32_t> kSIUnitVelocity{0x60A9, 0x00};

/// Velocity offset — rw, rpm
inline constexpr ObjectAddress<int32_t> kVelocityOffset{0x60B1, 0x00};

/// Torque offset — rw
inline constexpr ObjectAddress<int16_t> kTorqueOffset{0x60B2, 0x00};

/// Touch probe function — rw
inline constexpr ObjectAddress<uint16_t> kTouchProbeFunction{0x60B8, 0x00};

/// Touch probe status — ro
inline constexpr ObjectAddress<uint16_t> kTouchProbeStatus{0x60B9, 0x00};

/// Touch probe 1 positive edge — ro
inline constexpr ObjectAddress<int32_t> kTouchProbe1PositiveEdge{0x60BA, 0x00};

/// Touch probe 1 negative edge — ro
inline constexpr ObjectAddress<int32_t> kTouchProbe1NegativeEdge{0x60BB, 0x00};

/// Touch probe time stamp 1 positive value — ro
inline constexpr ObjectAddress<uint32_t> kTouchProbeTimeStamp1PositiveValue{0x60D1, 0x00};

/// Touch probe time stamp 1 negative value — ro
inline constexpr ObjectAddress<uint32_t> kTouchProbeTimeStamp1NegativeValue{0x60D2, 0x00};

/// Position option code — rw
inline constexpr ObjectAddress<uint16_t> kPositionOptionCode{0x60F2, 0x00};

/// Following error actual value — ro, Inc
inline constexpr ObjectAddress<int32_t> kFollowingErrorActualValue{0x60F4, 0x00};

/// Control effort — ro
inline constexpr ObjectAddress<int32_t> kControlEffort{0x60FA, 0x00};

/// Position demand internal value — ro, Inc
inline constexpr ObjectAddress<int32_t> kPositionDemandInternalValue{0x60FC, 0x00};

/// Digital inputs — ro
inline constexpr ObjectAddress<uint32_t> kDigitalInputs{0x60FD, 0x00};

/// Digital outputs / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kDigitalOutputsCount{0x60FE, 0x00};

/// Digital outputs / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kDigitalOutputsSubIndex001{0x60FE, 0x01};

/// Digital outputs / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kDigitalOutputsSubIndex002{0x60FE, 0x02};

/// Target velocity — rw, rpm
inline constexpr ObjectAddress<int32_t> kTargetVelocity{0x60FF, 0x00};

/// Supported drive modes — ro
inline constexpr ObjectAddress<uint32_t> kSupportedDriveModes{0x6502, 0x00};

/// Safe position actual value — ro
inline constexpr ObjectAddress<int32_t> kSafePositionActualValue{0x6611, 0x00};

/// Safe velocity actual value — ro
inline constexpr ObjectAddress<int32_t> kSafeVelocityActualValue{0x6613, 0x00};

/// Safe torque actual value — ro, mNm
inline constexpr ObjectAddress<int16_t> kSafeTorqueActualValue{0x6616, 0x00};

/// Safety statusword / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyStatuswordCount{0x6621, 0x00};

/// Safety statusword / SubIndex 001 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyStatuswordSubIndex001{0x6621, 0x01};

/// Safety statusword / SubIndex 002 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyStatuswordSubIndex002{0x6621, 0x02};

/// Safety statusword / SubIndex 003 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyStatuswordSubIndex003{0x6621, 0x03};

/// Safety statusword / SubIndex 004 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyStatuswordSubIndex004{0x6621, 0x04};

/// Restart acknowledge — rw
inline constexpr ObjectAddress<uint8_t> kRestartAcknowledge{0x6630, 0x00};

/// Error acknowledge — rw
inline constexpr ObjectAddress<uint8_t> kErrorAcknowledge{0x6632, 0x00};

/// STO command — rw
inline constexpr ObjectAddress<uint8_t> kSTOCommand{0x6640, 0x00};

/// STO restart — rw
inline constexpr ObjectAddress<uint8_t> kSTORestart{0x6641, 0x00};

/// SS1 command / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSS1CommandCount{0x6650, 0x00};

/// SS1 command / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSS1CommandSubIndex001{0x6650, 0x01};

/// t_SS1 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTSS1Count{0x6651, 0x00};

/// t_SS1 / SubIndex 001 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTSS1SubIndex001{0x6651, 0x01};

/// n_Zero_SS1 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kNZeroSS1Count{0x6653, 0x00};

/// n_Zero_SS1 / SubIndex 001 — rw, c/min
inline constexpr ObjectAddress<uint32_t> kNZeroSS1SubIndex001{0x6653, 0x01};

/// t_L_SS1 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTLSS1Count{0x6654, 0x00};

/// t_L_SS1 / SubIndex 001 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTLSS1SubIndex001{0x6654, 0x01};

/// a_SS1 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kASS1Count{0x6656, 0x00};

/// a_SS1 / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kASS1SubIndex001{0x6656, 0x01};

/// t_D_SS1 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTDSS1Count{0x6657, 0x00};

/// t_D_SS1 / SubIndex 001 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTDSS1SubIndex001{0x6657, 0x01};

/// SBC command — rw
inline constexpr ObjectAddress<uint8_t> kSBCCommand{0x6660, 0x00};

/// Brake time delay — rw, ms
inline constexpr ObjectAddress<uint16_t> kBrakeTimeDelay{0x6661, 0x00};

/// SOS command / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSOSCommandCount{0x6668, 0x00};

/// SOS command / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSOSCommandSubIndex001{0x6668, 0x01};

/// s_Zero_SOS / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSZeroSOSCount{0x666A, 0x00};

/// s_Zero_SOS / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kSZeroSOSSubIndex001{0x666A, 0x01};

/// n_Zero_SOS / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kNZeroSOSCount{0x666C, 0x00};

/// n_Zero_SOS / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kNZeroSOSSubIndex001{0x666C, 0x01};

/// SS2 command / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSS2CommandCount{0x6670, 0x00};

/// SS2 command / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSS2CommandSubIndex001{0x6670, 0x01};

/// t_SS2 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTSS2Count{0x6671, 0x00};

/// t_SS2 / SubIndex 001 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTSS2SubIndex001{0x6671, 0x01};

/// t_L_SS2 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTLSS2Count{0x6672, 0x00};

/// t_L_SS2 / SubIndex 001 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTLSS2SubIndex001{0x6672, 0x01};

/// a_SS2 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kASS2Count{0x6674, 0x00};

/// a_SS2 / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kASS2SubIndex001{0x6674, 0x01};

/// t_D_SS2 / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTDSS2Count{0x6675, 0x00};

/// t_D_SS2 / SubIndex 001 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTDSS2SubIndex001{0x6675, 0x01};

/// SOS restart / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSOSRestartCount{0x6676, 0x00};

/// SOS restart / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSOSRestartSubIndex001{0x6676, 0x01};

/// SS2 limit violation reaction / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSS2LimitViolationReactionCount{0x6677, 0x00};

/// SS2 limit violation reaction / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kSS2LimitViolationReactionSubIndex001{0x6677, 0x01};

/// SLS command / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSLSCommandCount{0x6690, 0x00};

/// SLS command / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSLSCommandSubIndex001{0x6690, 0x01};

/// SLS command / SubIndex 002 — rw
inline constexpr ObjectAddress<uint8_t> kSLSCommandSubIndex002{0x6690, 0x02};

/// SLS command / SubIndex 003 — rw
inline constexpr ObjectAddress<uint8_t> kSLSCommandSubIndex003{0x6690, 0x03};

/// SLS command / SubIndex 004 — rw
inline constexpr ObjectAddress<uint8_t> kSLSCommandSubIndex004{0x6690, 0x04};

/// t_SLS / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTSLSCount{0x6691, 0x00};

/// t_SLS / SubIndex 001 — rw
inline constexpr ObjectAddress<uint16_t> kTSLSSubIndex001{0x6691, 0x01};

/// t_SLS / SubIndex 002 — rw
inline constexpr ObjectAddress<uint16_t> kTSLSSubIndex002{0x6691, 0x02};

/// t_SLS / SubIndex 003 — rw
inline constexpr ObjectAddress<uint16_t> kTSLSSubIndex003{0x6691, 0x03};

/// t_SLS / SubIndex 004 — rw
inline constexpr ObjectAddress<uint16_t> kTSLSSubIndex004{0x6691, 0x04};

/// n_SLS / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kNSLSCount{0x6692, 0x00};

/// n_SLS / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kNSLSSubIndex001{0x6692, 0x01};

/// n_SLS / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kNSLSSubIndex002{0x6692, 0x02};

/// n_SLS / SubIndex 003 — rw
inline constexpr ObjectAddress<uint32_t> kNSLSSubIndex003{0x6692, 0x03};

/// n_SLS / SubIndex 004 — rw
inline constexpr ObjectAddress<uint32_t> kNSLSSubIndex004{0x6692, 0x04};

/// t_L_SLS / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTLSLSCount{0x6694, 0x00};

/// t_L_SLS / SubIndex 001 — rw
inline constexpr ObjectAddress<uint16_t> kTLSLSSubIndex001{0x6694, 0x01};

/// t_L_SLS / SubIndex 002 — rw
inline constexpr ObjectAddress<uint16_t> kTLSLSSubIndex002{0x6694, 0x02};

/// t_L_SLS / SubIndex 003 — rw
inline constexpr ObjectAddress<uint16_t> kTLSLSSubIndex003{0x6694, 0x03};

/// t_L_SLS / SubIndex 004 — rw
inline constexpr ObjectAddress<uint16_t> kTLSLSSubIndex004{0x6694, 0x04};

/// t_D_SLS / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTDSLSCount{0x6695, 0x00};

/// t_D_SLS / SubIndex 001 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTDSLSSubIndex001{0x6695, 0x01};

/// t_D_SLS / SubIndex 002 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTDSLSSubIndex002{0x6695, 0x02};

/// t_D_SLS / SubIndex 003 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTDSLSSubIndex003{0x6695, 0x03};

/// t_D_SLS / SubIndex 004 — rw, ms
inline constexpr ObjectAddress<uint16_t> kTDSLSSubIndex004{0x6695, 0x04};

/// a_SLS / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kASLSCount{0x6696, 0x00};

/// a_SLS / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kASLSSubIndex001{0x6696, 0x01};

/// a_SLS / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kASLSSubIndex002{0x6696, 0x02};

/// a_SLS / SubIndex 003 — rw
inline constexpr ObjectAddress<uint32_t> kASLSSubIndex003{0x6696, 0x03};

/// a_SLS / SubIndex 004 — rw
inline constexpr ObjectAddress<uint32_t> kASLSSubIndex004{0x6696, 0x04};

/// SLS Limit violation reaction / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSLSLimitViolationReactionCount{0x6698, 0x00};

/// SLS Limit violation reaction / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kSLSLimitViolationReactionSubIndex001{0x6698, 0x01};

/// SLS Limit violation reaction / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kSLSLimitViolationReactionSubIndex002{0x6698, 0x02};

/// SLS Limit violation reaction / SubIndex 003 — rw
inline constexpr ObjectAddress<uint32_t> kSLSLimitViolationReactionSubIndex003{0x6698, 0x03};

/// SLS Limit violation reaction / SubIndex 004 — rw
inline constexpr ObjectAddress<uint32_t> kSLSLimitViolationReactionSubIndex004{0x6698, 0x04};

/// n_pos_max — rw
inline constexpr ObjectAddress<int32_t> kNPosMax{0x66AA, 0x00};

/// n_neg_max — rw
inline constexpr ObjectAddress<int32_t> kNNegMax{0x66AC, 0x00};

/// SMS Limit violation reaction — rw
inline constexpr ObjectAddress<uint32_t> kSMSLimitViolationReaction{0x66AD, 0x00};

/// SLT command / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSLTCommandCount{0x66B0, 0x00};

/// SLT command / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSLTCommandSubIndex001{0x66B0, 0x01};

/// f_PosLim_SLT / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kFPosLimSLTCount{0x66B1, 0x00};

/// f_PosLim_SLT / SubIndex 001 — rw, mNm
inline constexpr ObjectAddress<int16_t> kFPosLimSLTSubIndex001{0x66B1, 0x01};

/// f_NegLim_SLT / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kFNegLimSLTCount{0x66B2, 0x00};

/// f_NegLim_SLT / SubIndex 001 — rw, mNm
inline constexpr ObjectAddress<int16_t> kFNegLimSLTSubIndex001{0x66B2, 0x01};

/// SLT limit violation reaction / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSLTLimitViolationReactionCount{0x66B3, 0x00};

/// SLT limit violation reaction / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kSLTLimitViolationReactionSubIndex001{0x66B3, 0x01};

/// FSoE Master Frame Elements / Subindex 000 — rw
inline constexpr ObjectAddress<uint8_t> kFSoEMasterFrameElementsCount{0x6760, 0x00};

/// FSoE Master Frame Elements / FSoE Command — rw
inline constexpr ObjectAddress<uint8_t> kFSoEMasterFrameElementsFSoECommand{0x6760, 0x01};

/// FSoE Master Frame Elements / FSoE ConnectionID — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoEConnectionID{0x6760, 0x02};

/// FSoE Master Frame Elements / FSoE CRC_0 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC0{0x6760, 0x03};

/// FSoE Master Frame Elements / FSoE CRC_1 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC1{0x6760, 0x04};

/// FSoE Master Frame Elements / FSoE CRC_2 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC2{0x6760, 0x05};

/// FSoE Master Frame Elements / FSoE CRC_3 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC3{0x6760, 0x06};

/// FSoE Master Frame Elements / FSoE CRC_4 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC4{0x6760, 0x07};

/// FSoE Master Frame Elements / FSoE CRC_5 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC5{0x6760, 0x08};

/// FSoE Master Frame Elements / FSoE CRC_6 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC6{0x6760, 0x09};

/// FSoE Master Frame Elements / FSoE CRC_7 — rw
inline constexpr ObjectAddress<uint16_t> kFSoEMasterFrameElementsFSoECRC7{0x6760, 0x0A};

/// FSoE Slave Frame Elements / Subindex 000 — rw
inline constexpr ObjectAddress<uint8_t> kFSoESlaveFrameElementsCount{0x6770, 0x00};

/// FSoE Slave Frame Elements / FSoE Command — rw
inline constexpr ObjectAddress<uint8_t> kFSoESlaveFrameElementsFSoECommand{0x6770, 0x01};

/// FSoE Slave Frame Elements / FSoE ConnectionID — rw
inline constexpr ObjectAddress<uint16_t> kFSoESlaveFrameElementsFSoEConnectionID{0x6770, 0x02};

/// FSoE Slave Frame Elements / FSoE CRC_0 — rw
inline constexpr ObjectAddress<uint16_t> kFSoESlaveFrameElementsFSoECRC0{0x6770, 0x03};

/// FSoE Slave Frame Elements / FSoE CRC_1 — rw
inline constexpr ObjectAddress<uint16_t> kFSoESlaveFrameElementsFSoECRC1{0x6770, 0x04};

}  // namespace mm::node::cia402::objects
