// Generated by `motion-master generate-object-addresses` from somanet-v5.6.6.xml — do not edit.
// Regenerating is a two-step job: run that command, then `tools/format.sh` — clang-format
// wraps the declarations that overrun 100 columns, and it does so context-sensitively
// enough that reproducing its choices here would be guesswork.
//
// CiA 301 communication area (0x1xxx) and the standard MDP objects — 222 addresses.
//
// Each constant carries an object's index, subindex and the C++ type its declared
// ETG.1020 type maps to, so a call site cannot disagree with the object it names:
//
//     device.value(objects::kStatusword)        // std::optional<uint16_t>
//     device.readValue(objects::kDeviceName)    // std::expected<std::string, ...>
//
// The union of every device in the ESI is emitted: which module is fitted is unknowable
// offline, so an address that does not apply to the drive in front of you simply fails
// to resolve at runtime, exactly as a hand-written index would. The trailing comment on
// each line is the ESI's own name, access mode and unit — the unit especially, since a
// temperature in milli-degrees looks exactly like one in degrees until a motor stops.

#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "node/device_parameter.h"

namespace mm::node::profile::objects {

/// Device type — ro
inline constexpr ObjectAddress<uint32_t> kDeviceType{0x1000, 0x00};

/// Error register — ro
inline constexpr ObjectAddress<uint8_t> kErrorRegister{0x1001, 0x00};

/// COB-ID SYNC — rw
inline constexpr ObjectAddress<int32_t> kCOBIDSYNC{0x1005, 0x00};

/// Communication cycle period — rw
inline constexpr ObjectAddress<int32_t> kCommunicationCyclePeriod{0x1006, 0x00};

/// Manufacturer device name — ro
inline constexpr ObjectAddress<std::string> kManufacturerDeviceName{0x1008, 0x00};

/// Manufacturer software version — ro
inline constexpr ObjectAddress<std::string> kManufacturerSoftwareVersion{0x100A, 0x00};

/// Guard time — rw
inline constexpr ObjectAddress<uint16_t> kGuardTime{0x100C, 0x00};

/// Life time factor — rw
inline constexpr ObjectAddress<uint8_t> kLifeTimeFactor{0x100D, 0x00};

/// Store parameters / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kStoreParametersCount{0x1010, 0x00};

/// Store parameters / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kStoreParametersSubIndex001{0x1010, 0x01};

/// Restore default parameters / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kRestoreDefaultParametersCount{0x1011, 0x00};

/// Restore default parameters / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kRestoreDefaultParametersSubIndex001{0x1011, 0x01};

/// Restore default parameters / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kRestoreDefaultParametersSubIndex002{0x1011, 0x02};

/// Restore default parameters / SubIndex 003 — rw
inline constexpr ObjectAddress<uint32_t> kRestoreDefaultParametersSubIndex003{0x1011, 0x03};

/// Restore default parameters / SubIndex 004 — rw
inline constexpr ObjectAddress<uint32_t> kRestoreDefaultParametersSubIndex004{0x1011, 0x04};

/// Consumer heartbeat time / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kConsumerHeartbeatTimeCount{0x1016, 0x00};

/// Consumer heartbeat time / SubIndex 001 — rw
inline constexpr ObjectAddress<int32_t> kConsumerHeartbeatTimeSubIndex001{0x1016, 0x01};

/// Producer heartbeat time — rw
inline constexpr ObjectAddress<uint16_t> kProducerHeartbeatTime{0x1017, 0x00};

/// Identity object / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kIdentityObjectCount{0x1018, 0x00};

/// Identity object / Vendor ID — ro
inline constexpr ObjectAddress<uint32_t> kIdentityObjectVendorID{0x1018, 0x01};

/// Identity object / Product Code — ro
inline constexpr ObjectAddress<uint32_t> kIdentityObjectProductCode{0x1018, 0x02};

/// Identity object / Revision number — ro
inline constexpr ObjectAddress<uint32_t> kIdentityObjectRevisionNumber{0x1018, 0x03};

/// Identity object / Serial number — ro
inline constexpr ObjectAddress<uint32_t> kIdentityObjectSerialNumber{0x1018, 0x04};

/// Synchronous counter overflow value — rw
inline constexpr ObjectAddress<uint8_t> kSynchronousCounterOverflowValue{0x1019, 0x00};

/// OS command / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kOSCommandCount{0x1023, 0x00};

/// OS command / Command — rw
inline constexpr ObjectAddress<std::vector<uint8_t>> kOSCommandCommand{0x1023, 0x01};

/// OS command / Status — ro
inline constexpr ObjectAddress<uint8_t> kOSCommandStatus{0x1023, 0x02};

/// OS command / Response — ro
inline constexpr ObjectAddress<std::vector<uint8_t>> kOSCommandResponse{0x1023, 0x03};

/// OS command mode — wo
inline constexpr ObjectAddress<uint8_t> kOSCommandMode{0x1024, 0x00};

/// Receive PDO1 parameter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kReceivePDO1ParameterCount{0x1400, 0x00};

/// Receive PDO1 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1ParameterCOBIDUsedByPDO{0x1400, 0x01};

/// Receive PDO1 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO1ParameterTransmissionType{0x1400, 0x02};

/// Receive PDO1 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kReceivePDO1ParameterInhibitTime{0x1400, 0x03};

/// Receive PDO2 parameter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kReceivePDO2ParameterCount{0x1401, 0x00};

/// Receive PDO2 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO2ParameterCOBIDUsedByPDO{0x1401, 0x01};

/// Receive PDO2 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO2ParameterTransmissionType{0x1401, 0x02};

/// Receive PDO2 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kReceivePDO2ParameterInhibitTime{0x1401, 0x03};

/// Receive PDO3 parameter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kReceivePDO3ParameterCount{0x1402, 0x00};

/// Receive PDO3 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO3ParameterCOBIDUsedByPDO{0x1402, 0x01};

/// Receive PDO3 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO3ParameterTransmissionType{0x1402, 0x02};

/// Receive PDO3 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kReceivePDO3ParameterInhibitTime{0x1402, 0x03};

/// Receive PDO4 parameter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kReceivePDO4ParameterCount{0x1403, 0x00};

/// Receive PDO4 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO4ParameterCOBIDUsedByPDO{0x1403, 0x01};

/// Receive PDO4 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO4ParameterTransmissionType{0x1403, 0x02};

/// Receive PDO4 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kReceivePDO4ParameterInhibitTime{0x1403, 0x03};

/// Receive PDO1 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO1MappingCount{0x1600, 0x00};

/// Receive PDO1 mapping / Controlword — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1MappingControlword{0x1600, 0x01};

/// Receive PDO1 mapping / Modes of operation — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1MappingModesOfOperation{0x1600, 0x02};

/// Receive PDO1 mapping / Target Torque — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1MappingTargetTorque{0x1600, 0x03};

/// Receive PDO1 mapping / Target position — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1MappingTargetPosition{0x1600, 0x04};

/// Receive PDO1 mapping / Target velocity — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1MappingTargetVelocity{0x1600, 0x05};

/// Receive PDO1 mapping / Torque offset — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1MappingTorqueOffset{0x1600, 0x06};

/// Receive PDO1 mapping / Tuning command — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO1MappingTuningCommand{0x1600, 0x07};

/// Receive PDO2 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO2MappingCount{0x1601, 0x00};

/// Receive PDO2 mapping / Physical outputs — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO2MappingPhysicalOutputs{0x1601, 0x01};

/// Receive PDO2 mapping / Bit mask — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO2MappingBitMask{0x1601, 0x02};

/// Receive PDO3 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO3MappingCount{0x1602, 0x00};

/// Receive PDO3 mapping / User MOSI — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO3MappingUserMOSI{0x1602, 0x01};

/// Receive PDO3 mapping / Velocity offset — rw
inline constexpr ObjectAddress<uint32_t> kReceivePDO3MappingVelocityOffset{0x1602, 0x02};

/// Receive PDO4 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kReceivePDO4MappingCount{0x1603, 0x00};

/// Receive safe PDO1 mapping / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kReceiveSafePDO1MappingCount{0x1700, 0x00};

/// Receive safe PDO1 mapping / FSoE Command — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingFSoECommand{0x1700, 0x01};

/// Receive safe PDO1 mapping / STO — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSTO{0x1700, 0x02};

/// Receive safe PDO1 mapping / SS1 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSS1{0x1700, 0x03};

/// Receive safe PDO1 mapping / SS2 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSS2{0x1700, 0x04};

/// Receive safe PDO1 mapping / SOS — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSOS{0x1700, 0x05};

/// Receive safe PDO1 mapping / RxPadding 001 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding001{0x1700, 0x06};

/// Receive safe PDO1 mapping / RxPadding 002 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding002{0x1700, 0x07};

/// Receive safe PDO1 mapping / RxPadding 003 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding003{0x1700, 0x08};

/// Receive safe PDO1 mapping / Error acknowledge — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingErrorAcknowledge{0x1700, 0x09};

/// Receive safe PDO1 mapping / SLS Instance 1 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSLSInstance1{0x1700, 0x0A};

/// Receive safe PDO1 mapping / SLS Instance 2 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSLSInstance2{0x1700, 0x0B};

/// Receive safe PDO1 mapping / SLS Instance 3 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSLSInstance3{0x1700, 0x0C};

/// Receive safe PDO1 mapping / SLS Instance 4 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSLSInstance4{0x1700, 0x0D};

/// Receive safe PDO1 mapping / Restart acknowledge — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRestartAcknowledge{0x1700, 0x0E};

/// Receive safe PDO1 mapping / SBC command — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSBCCommand{0x1700, 0x0F};

/// Receive safe PDO1 mapping / Reset position — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingResetPosition{0x1700, 0x10};

/// Receive safe PDO1 mapping / SLT — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSLT{0x1700, 0x11};

/// Receive safe PDO1 mapping / FSoE CRC_0 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingFSoECRC0{0x1700, 0x12};

/// Receive safe PDO1 mapping / RxPadding 004 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding004{0x1700, 0x13};

/// Receive safe PDO1 mapping / RxPadding 005 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding005{0x1700, 0x14};

/// Receive safe PDO1 mapping / RxPadding 006 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding006{0x1700, 0x15};

/// Receive safe PDO1 mapping / RxPadding 007 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding007{0x1700, 0x16};

/// Receive safe PDO1 mapping / RxPadding 008 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding008{0x1700, 0x17};

/// Receive safe PDO1 mapping / Safe output 1 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSafeOutput1{0x1700, 0x18};

/// Receive safe PDO1 mapping / Safe output 2 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingSafeOutput2{0x1700, 0x19};

/// Receive safe PDO1 mapping / RxPadding 009 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding009{0x1700, 0x1A};

/// Receive safe PDO1 mapping / RxPadding 010 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingRxPadding010{0x1700, 0x1B};

/// Receive safe PDO1 mapping / FSoE CRC_1 — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingFSoECRC1{0x1700, 0x1C};

/// Receive safe PDO1 mapping / FSoE ConnectionID — ro
inline constexpr ObjectAddress<uint32_t> kReceiveSafePDO1MappingFSoEConnectionID{0x1700, 0x1D};

/// Transmit PDO1 parameter / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTransmitPDO1ParameterCount{0x1800, 0x00};

/// Transmit PDO1 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO1ParameterCOBIDUsedByPDO{0x1800, 0x01};

/// Transmit PDO1 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO1ParameterTransmissionType{0x1800, 0x02};

/// Transmit PDO1 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO1ParameterInhibitTime{0x1800, 0x03};

/// Transmit PDO1 parameter / reserved — ro
inline constexpr ObjectAddress<uint8_t> kTransmitPDO1ParameterReserved{0x1800, 0x04};

/// Transmit PDO1 parameter / Event timer — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO1ParameterEventTimer{0x1800, 0x05};

/// Transmit PDO2 parameter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTransmitPDO2ParameterCount{0x1801, 0x00};

/// Transmit PDO2 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO2ParameterCOBIDUsedByPDO{0x1801, 0x01};

/// Transmit PDO2 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO2ParameterTransmissionType{0x1801, 0x02};

/// Transmit PDO2 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO2ParameterInhibitTime{0x1801, 0x03};

/// Transmit PDO2 parameter / reserved — ro
inline constexpr ObjectAddress<uint8_t> kTransmitPDO2ParameterReserved{0x1801, 0x04};

/// Transmit PDO2 parameter / Event timer — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO2ParameterEventTimer{0x1801, 0x05};

/// Transmit PDO3 parameter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTransmitPDO3ParameterCount{0x1802, 0x00};

/// Transmit PDO3 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO3ParameterCOBIDUsedByPDO{0x1802, 0x01};

/// Transmit PDO3 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO3ParameterTransmissionType{0x1802, 0x02};

/// Transmit PDO3 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO3ParameterInhibitTime{0x1802, 0x03};

/// Transmit PDO3 parameter / reserved — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO3ParameterReserved{0x1802, 0x04};

/// Transmit PDO3 parameter / Event timer — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO3ParameterEventTimer{0x1802, 0x05};

/// Transmit PDO4 parameter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTransmitPDO4ParameterCount{0x1803, 0x00};

/// Transmit PDO4 parameter / COB-ID used by PDO — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO4ParameterCOBIDUsedByPDO{0x1803, 0x01};

/// Transmit PDO4 parameter / Transmission type — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO4ParameterTransmissionType{0x1803, 0x02};

/// Transmit PDO4 parameter / Inhibit time — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO4ParameterInhibitTime{0x1803, 0x03};

/// Transmit PDO4 parameter / reserved — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO4ParameterReserved{0x1803, 0x04};

/// Transmit PDO4 parameter / Event timer — rw
inline constexpr ObjectAddress<uint16_t> kTransmitPDO4ParameterEventTimer{0x1803, 0x05};

/// Transmit PDO1 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO1MappingCount{0x1A00, 0x00};

/// Transmit PDO1 mapping / Statusword — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO1MappingStatusword{0x1A00, 0x01};

/// Transmit PDO1 mapping / Modes of operation display — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO1MappingModesOfOperationDisplay{0x1A00, 0x02};

/// Transmit PDO1 mapping / Position actual value — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO1MappingPositionActualValue{0x1A00, 0x03};

/// Transmit PDO1 mapping / Velocity actual value — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO1MappingVelocityActualValue{0x1A00, 0x04};

/// Transmit PDO1 mapping / Torque actual value — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO1MappingTorqueActualValue{0x1A00, 0x05};

/// Transmit PDO2 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO2MappingCount{0x1A01, 0x00};

/// Transmit PDO2 mapping / Analog input 1 — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO2MappingAnalogInput1{0x1A01, 0x01};

/// Transmit PDO2 mapping / Analog input 2 — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO2MappingAnalogInput2{0x1A01, 0x02};

/// Transmit PDO2 mapping / Analog input 3 — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO2MappingAnalogInput3{0x1A01, 0x03};

/// Transmit PDO2 mapping / Analog input 4 — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO2MappingAnalogInput4{0x1A01, 0x04};

/// Transmit PDO2 mapping / Tuning status — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO2MappingTuningStatus{0x1A01, 0x05};

/// Transmit PDO3 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO3MappingCount{0x1A02, 0x00};

/// Transmit PDO3 mapping / Digital inputs — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO3MappingDigitalInputs{0x1A02, 0x01};

/// Transmit PDO4 mapping / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kTransmitPDO4MappingCount{0x1A03, 0x00};

/// Transmit PDO4 mapping / User MISO — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO4MappingUserMISO{0x1A03, 0x01};

/// Transmit PDO4 mapping / Timestamp — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO4MappingTimestamp{0x1A03, 0x02};

/// Transmit PDO4 mapping / Position demand internal value — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO4MappingPositionDemandInternalValue{0x1A03,
                                                                                         0x03};

/// Transmit PDO4 mapping / Velocity demand value — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO4MappingVelocityDemandValue{0x1A03, 0x04};

/// Transmit PDO4 mapping / Torque demand — rw
inline constexpr ObjectAddress<uint32_t> kTransmitPDO4MappingTorqueDemand{0x1A03, 0x05};

/// Transmit safe PDO1 mapping / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTransmitSafePDO1MappingCount{0x1B00, 0x00};

/// Transmit safe PDO1 mapping / FSoE Command — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECommand{0x1B00, 0x01};

/// Transmit safe PDO1 mapping / STO state — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSTOState{0x1B00, 0x02};

/// Transmit safe PDO1 mapping / TxPadding 001 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTxPadding001{0x1B00, 0x03};

/// Transmit safe PDO1 mapping / TxPadding 002 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTxPadding002{0x1B00, 0x04};

/// Transmit safe PDO1 mapping / SOS state — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSOSState{0x1B00, 0x05};

/// Transmit safe PDO1 mapping / TxPadding 003 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTxPadding003{0x1B00, 0x06};

/// Transmit safe PDO1 mapping / TxPadding 004 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTxPadding004{0x1B00, 0x07};

/// Transmit safe PDO1 mapping / TxPadding 005 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTxPadding005{0x1B00, 0x08};

/// Transmit safe PDO1 mapping / Error state — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingErrorState{0x1B00, 0x09};

/// Transmit safe PDO1 mapping / SS1 state — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSS1State{0x1B00, 0x0A};

/// Transmit safe PDO1 mapping / SS2 state — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSS2State{0x1B00, 0x0B};

/// Transmit safe PDO1 mapping / TxPadding 006 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTxPadding006{0x1B00, 0x0C};

/// Transmit safe PDO1 mapping / TxPadding 007 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTxPadding007{0x1B00, 0x0D};

/// Transmit safe PDO1 mapping / SLS Instance 1 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSLSInstance1{0x1B00, 0x0E};

/// Transmit safe PDO1 mapping / SLS Instance 2 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSLSInstance2{0x1B00, 0x0F};

/// Transmit safe PDO1 mapping / SLS Instance 3 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSLSInstance3{0x1B00, 0x10};

/// Transmit safe PDO1 mapping / SLS Instance 4 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSLSInstance4{0x1B00, 0x11};

/// Transmit safe PDO1 mapping / FSoE CRC_0 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC0{0x1B00, 0x12};

/// Transmit safe PDO1 mapping / Restart acknowledge required — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingRestartAcknowledgeRequired{0x1B00,
                                                                                            0x13};

/// Transmit safe PDO1 mapping / SBC state — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSBCState{0x1B00, 0x14};

/// Transmit safe PDO1 mapping / Temperature warning — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingTemperatureWarning{0x1B00, 0x15};

/// Transmit safe PDO1 mapping / Safe position valid — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafePositionValid{0x1B00, 0x16};

/// Transmit safe PDO1 mapping / Safe speed valid — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeSpeedValid{0x1B00, 0x17};

/// Transmit safe PDO1 mapping / Safe torque valid — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeTorqueValid{0x1B00, 0x18};

/// Transmit safe PDO1 mapping / Safe torque sign valid — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeTorqueSignValid{0x1B00, 0x19};

/// Transmit safe PDO1 mapping / SLT state — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSLTState{0x1B00, 0x1A};

/// Transmit safe PDO1 mapping / Safe input 1 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeInput1{0x1B00, 0x1B};

/// Transmit safe PDO1 mapping / Safe input 2 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeInput2{0x1B00, 0x1C};

/// Transmit safe PDO1 mapping / Safe input 3 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeInput3{0x1B00, 0x1D};

/// Transmit safe PDO1 mapping / Safe input 4 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeInput4{0x1B00, 0x1E};

/// Transmit safe PDO1 mapping / Safe output monitor 1 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeOutputMonitor1{0x1B00, 0x1F};

/// Transmit safe PDO1 mapping / Safe output monitor 2 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeOutputMonitor2{0x1B00, 0x20};

/// Transmit safe PDO1 mapping / Analog diagnostic active (single channel) — ro
inline constexpr ObjectAddress<uint32_t>
    kTransmitSafePDO1MappingAnalogDiagnosticActiveSingleChannel{0x1B00, 0x21};

/// Transmit safe PDO1 mapping / Analog value valid — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingAnalogValueValid{0x1B00, 0x22};

/// Transmit safe PDO1 mapping / FSoE CRC_1 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC1{0x1B00, 0x23};

/// Transmit safe PDO1 mapping / Safe position actual value low — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafePositionActualValueLow{0x1B00,
                                                                                            0x24};

/// Transmit safe PDO1 mapping / FSoE CRC_2 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC2{0x1B00, 0x25};

/// Transmit safe PDO1 mapping / Safe position actual value high — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafePositionActualValueHigh{0x1B00,
                                                                                             0x26};

/// Transmit safe PDO1 mapping / FSoE CRC_3 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC3{0x1B00, 0x27};

/// Transmit safe PDO1 mapping / Safe velocity actual value low — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeVelocityActualValueLow{0x1B00,
                                                                                            0x28};

/// Transmit safe PDO1 mapping / FSoE CRC_4 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC4{0x1B00, 0x29};

/// Transmit safe PDO1 mapping / Safe velocity actual value high — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeVelocityActualValueHigh{0x1B00,
                                                                                             0x2A};

/// Transmit safe PDO1 mapping / FSoE CRC_5 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC5{0x1B00, 0x2B};

/// Transmit safe PDO1 mapping / Safe analog value (scaled) — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeAnalogValueScaled{0x1B00,
                                                                                       0x2C};

/// Transmit safe PDO1 mapping / FSoE CRC_6 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC6{0x1B00, 0x2D};

/// Transmit safe PDO1 mapping / Safe torque — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingSafeTorque{0x1B00, 0x2E};

/// Transmit safe PDO1 mapping / FSoE CRC_7 — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoECRC7{0x1B00, 0x2F};

/// Transmit safe PDO1 mapping / FSoE ConnectionID — ro
inline constexpr ObjectAddress<uint32_t> kTransmitSafePDO1MappingFSoEConnectionID{0x1B00, 0x30};

/// Sync manager type / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSyncManagerTypeCount{0x1C00, 0x00};

/// Sync manager type / SubIndex 001 — ro
inline constexpr ObjectAddress<uint8_t> kSyncManagerTypeSubIndex001{0x1C00, 0x01};

/// Sync manager type / SubIndex 002 — ro
inline constexpr ObjectAddress<uint8_t> kSyncManagerTypeSubIndex002{0x1C00, 0x02};

/// Sync manager type / SubIndex 003 — ro
inline constexpr ObjectAddress<uint8_t> kSyncManagerTypeSubIndex003{0x1C00, 0x03};

/// Sync manager type / SubIndex 004 — ro
inline constexpr ObjectAddress<uint8_t> kSyncManagerTypeSubIndex004{0x1C00, 0x04};

/// SM 0 Assignment / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSM0AssignmentCount{0x1C10, 0x00};

/// SM 1 Assignment / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSM1AssignmentCount{0x1C11, 0x00};

/// SM 2 Assignment / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kSM2AssignmentCount{0x1C12, 0x00};

/// SM 2 Assignment / SubIndex 001 — rw
inline constexpr ObjectAddress<uint16_t> kSM2AssignmentSubIndex001{0x1C12, 0x01};

/// SM 2 Assignment / SubIndex 002 — rw
inline constexpr ObjectAddress<uint16_t> kSM2AssignmentSubIndex002{0x1C12, 0x02};

/// SM 2 Assignment / SubIndex 003 — rw
inline constexpr ObjectAddress<uint16_t> kSM2AssignmentSubIndex003{0x1C12, 0x03};

/// SM 2 Assignment / SubIndex 004 — rw
inline constexpr ObjectAddress<uint16_t> kSM2AssignmentSubIndex004{0x1C12, 0x04};

/// SM 2 Assignment / SubIndex 005 — rw
inline constexpr ObjectAddress<uint16_t> kSM2AssignmentSubIndex005{0x1C12, 0x05};

/// SM 3 Assignment / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kSM3AssignmentCount{0x1C13, 0x00};

/// SM 3 Assignment / SubIndex 001 — rw
inline constexpr ObjectAddress<uint16_t> kSM3AssignmentSubIndex001{0x1C13, 0x01};

/// SM 3 Assignment / SubIndex 002 — rw
inline constexpr ObjectAddress<uint16_t> kSM3AssignmentSubIndex002{0x1C13, 0x02};

/// SM 3 Assignment / SubIndex 003 — rw
inline constexpr ObjectAddress<uint16_t> kSM3AssignmentSubIndex003{0x1C13, 0x03};

/// SM 3 Assignment / SubIndex 004 — rw
inline constexpr ObjectAddress<uint16_t> kSM3AssignmentSubIndex004{0x1C13, 0x04};

/// SM 3 Assignment / SubIndex 005 — rw
inline constexpr ObjectAddress<uint16_t> kSM3AssignmentSubIndex005{0x1C13, 0x05};

/// SM 3 Assignment / SubIndex 006 — rw
inline constexpr ObjectAddress<uint16_t> kSM3AssignmentSubIndex006{0x1C13, 0x06};

/// Output SyncManager Parameter / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kOutputSyncManagerParameterCount{0x1C32, 0x00};

/// Output SyncManager Parameter / Synchronization Type — ro
inline constexpr ObjectAddress<uint16_t> kOutputSyncManagerParameterSynchronizationType{0x1C32,
                                                                                        0x01};

/// Output SyncManager Parameter / Cycle time — ro
inline constexpr ObjectAddress<uint32_t> kOutputSyncManagerParameterCycleTime{0x1C32, 0x02};

/// Output SyncManager Parameter / Shift time — ro
inline constexpr ObjectAddress<uint32_t> kOutputSyncManagerParameterShiftTime{0x1C32, 0x03};

/// Output SyncManager Parameter / Synchronization types supported — ro
inline constexpr ObjectAddress<uint16_t> kOutputSyncManagerParameterSynchronizationTypesSupported{
    0x1C32, 0x04};

/// Input SyncManager Parameter / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kInputSyncManagerParameterCount{0x1C33, 0x00};

/// Input SyncManager Parameter / Synchronization Type — ro
inline constexpr ObjectAddress<uint16_t> kInputSyncManagerParameterSynchronizationType{0x1C33,
                                                                                       0x01};

/// Input SyncManager Parameter / Cycle time — ro
inline constexpr ObjectAddress<uint32_t> kInputSyncManagerParameterCycleTime{0x1C33, 0x02};

/// Input SyncManager Parameter / Shift time — ro
inline constexpr ObjectAddress<uint32_t> kInputSyncManagerParameterShiftTime{0x1C33, 0x03};

/// Input SyncManager Parameter / Synchronization types supported — ro
inline constexpr ObjectAddress<uint16_t> kInputSyncManagerParameterSynchronizationTypesSupported{
    0x1C33, 0x04};

/// Modular Device Profile / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kModularDeviceProfileCount{0xF000, 0x00};

/// Modular Device Profile / Index distance — rw
inline constexpr ObjectAddress<uint16_t> kModularDeviceProfileIndexDistance{0xF000, 0x01};

/// Modular Device Profile / Maximum number of modules — rw
inline constexpr ObjectAddress<uint16_t> kModularDeviceProfileMaximumNumberOfModules{0xF000, 0x02};

/// Configured module ident list / SubIndex 000 — rw
inline constexpr ObjectAddress<uint8_t> kConfiguredModuleIdentListCount{0xF030, 0x00};

/// Configured module ident list / SubIndex 001 — rw
inline constexpr ObjectAddress<uint32_t> kConfiguredModuleIdentListSubIndex001{0xF030, 0x01};

/// Configured module ident list / SubIndex 002 — rw
inline constexpr ObjectAddress<uint32_t> kConfiguredModuleIdentListSubIndex002{0xF030, 0x02};

/// Detected module ident list / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kDetectedModuleIdentListCount{0xF050, 0x00};

/// Detected module ident list / SubIndex 001 — ro
inline constexpr ObjectAddress<uint32_t> kDetectedModuleIdentListSubIndex001{0xF050, 0x01};

/// Detected module ident list / SubIndex 002 — ro
inline constexpr ObjectAddress<uint32_t> kDetectedModuleIdentListSubIndex002{0xF050, 0x02};

}  // namespace mm::node::profile::objects
