// Generated by `motion-master generate-object-addresses` from somanet-v5.6.6.xml — do not edit.
// Regenerating is a two-step job: run that command, then `tools/format.sh` — clang-format
// wraps the declarations that overrun 100 columns, and it does so context-sensitively
// enough that reproducing its choices here would be guesswork.
//
// SOMANET vendor area (0x2xxx) and FSoE — 423 addresses.
//
// Each constant carries an object's index, subindex and the C++ type its declared
// ETG.1020 type maps to, so a call site cannot disagree with the object it names:
//
//     device.value(objects::kStatusword)        // std::optional<uint16_t>
//     device.readValue(objects::kDeviceName)    // std::expected<std::string, ...>
//
// The union of every device in the ESI is emitted: which module is fitted is unknowable
// offline, so an address that does not apply to the drive in front of you simply fails
// to resolve at runtime, exactly as a hand-written index would. The trailing comment on
// each line is the ESI's own name, access mode and unit — the unit especially, since a
// temperature in milli-degrees looks exactly like one in degrees until a motor stops.

#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "node/device_parameter.h"

namespace mm::node::somanet::objects {

/// Command object (disabled) — rw
inline constexpr ObjectAddress<uint16_t> kCommandObjectDisabled{0x2000, 0x00};

/// Commutation angle offset — rw
inline constexpr ObjectAddress<int16_t> kCommutationAngleOffset{0x2001, 0x00};

/// Position control strategy — rw
inline constexpr ObjectAddress<uint16_t> kPositionControlStrategy{0x2002, 0x00};

/// Motor specific settings / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kMotorSpecificSettingsCount{0x2003, 0x00};

/// Motor specific settings / Pole pairs — rw
inline constexpr ObjectAddress<uint8_t> kMotorSpecificSettingsPolePairs{0x2003, 0x01};

/// Motor specific settings / Torque constant — rw, μNm/A
inline constexpr ObjectAddress<int32_t> kMotorSpecificSettingsTorqueConstant{0x2003, 0x02};

/// Motor specific settings / Phase resistance — rw, μΩ
inline constexpr ObjectAddress<int32_t> kMotorSpecificSettingsPhaseResistance{0x2003, 0x03};

/// Motor specific settings / Phase inductance — rw, μH
inline constexpr ObjectAddress<int32_t> kMotorSpecificSettingsPhaseInductance{0x2003, 0x04};

/// Motor specific settings / Motor phases inverted — rw
inline constexpr ObjectAddress<uint8_t> kMotorSpecificSettingsMotorPhasesInverted{0x2003, 0x05};

/// Motor specific settings / Difference of Ld and Lq inductance — rw, μH
inline constexpr ObjectAddress<uint32_t> kMotorSpecificSettingsDifferenceOfLdAndLqInductance{0x2003,
                                                                                             0x06};

/// Brake options / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kBrakeOptionsCount{0x2004, 0x00};

/// Brake options / Pull voltage — rw, mV
inline constexpr ObjectAddress<uint32_t> kBrakeOptionsPullVoltage{0x2004, 0x01};

/// Brake options / Hold voltage — rw, mV
inline constexpr ObjectAddress<uint32_t> kBrakeOptionsHoldVoltage{0x2004, 0x02};

/// Brake options / Pull time — rw, ms
inline constexpr ObjectAddress<uint16_t> kBrakeOptionsPullTime{0x2004, 0x03};

/// Brake options / Release strategy — rw
inline constexpr ObjectAddress<uint8_t> kBrakeOptionsReleaseStrategy{0x2004, 0x04};

/// Brake options / Controller disable delay — rw, ms
inline constexpr ObjectAddress<uint16_t> kBrakeOptionsControllerDisableDelay{0x2004, 0x05};

/// Brake options / DC bus voltage (deprecated) — ro, V
inline constexpr ObjectAddress<uint16_t> kBrakeOptionsDCBusVoltageDeprecated{0x2004, 0x06};

/// Brake options / Brake status — rw
inline constexpr ObjectAddress<uint8_t> kBrakeOptionsBrakeStatus{0x2004, 0x07};

/// Brake options / Minimum displacement (pin brake) — rw, Inc
inline constexpr ObjectAddress<uint32_t> kBrakeOptionsMinimumDisplacementPinBrake{0x2004, 0x08};

/// Brake options / Percentage of Rated Current (pin brake) — rw
inline constexpr ObjectAddress<uint16_t> kBrakeOptionsPercentageOfRatedCurrentPinBrake{0x2004,
                                                                                       0x09};

/// Brake options / Output voltage — rw, mV
inline constexpr ObjectAddress<uint16_t> kBrakeOptionsOutputVoltage{0x2004, 0x0A};

/// Brake options / Switching frequency — rw
inline constexpr ObjectAddress<uint8_t> kBrakeOptionsSwitchingFrequency{0x2004, 0x0B};

/// Brake options / Initial movement direction (pin brake) — rw
inline constexpr ObjectAddress<int8_t> kBrakeOptionsInitialMovementDirectionPinBrake{0x2004, 0x0C};

/// Homing Options / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kHomingOptionsCount{0x2005, 0x00};

/// Homing Options / Home Position — ro, Inc
inline constexpr ObjectAddress<int32_t> kHomingOptionsHomePosition{0x2005, 0x01};

/// Homing Options / Restore Home Position when loading configuration — rw
inline constexpr ObjectAddress<uint8_t> kHomingOptionsRestoreHomePositionWhenLoadingConfiguration{
    0x2005, 0x02};

/// Homing Options / Torque Threshold for Homing on end stop — rw
inline constexpr ObjectAddress<uint16_t> kHomingOptionsTorqueThresholdForHomingOnEndStop{0x2005,
                                                                                         0x03};

/// Homing Options / Offset From Endstop — rw, Inc
inline constexpr ObjectAddress<uint16_t> kHomingOptionsOffsetFromEndstop{0x2005, 0x04};

/// Protection / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kProtectionCount{0x2006, 0x00};

/// Protection / Undervoltage setpoint — rw, V
inline constexpr ObjectAddress<int32_t> kProtectionUndervoltageSetpoint{0x2006, 0x01};

/// Protection / Overvoltage setpoint — rw, V
inline constexpr ObjectAddress<int32_t> kProtectionOvervoltageSetpoint{0x2006, 0x02};

/// Protection / Overcurrent setpoint — rw, mA
inline constexpr ObjectAddress<int32_t> kProtectionOvercurrentSetpoint{0x2006, 0x03};

/// Cogging torque compensation / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kCoggingTorqueCompensationCount{0x2008, 0x00};

/// Cogging torque compensation / State — ro
inline constexpr ObjectAddress<int16_t> kCoggingTorqueCompensationState{0x2008, 0x01};

/// Cogging torque compensation / Enabled — rw
inline constexpr ObjectAddress<int16_t> kCoggingTorqueCompensationEnabled{0x2008, 0x02};

/// Commutation offset / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kCommutationOffsetCount{0x2009, 0x00};

/// Commutation offset / State — rw
inline constexpr ObjectAddress<int16_t> kCommutationOffsetState{0x2009, 0x01};

/// Commutation offset / Applied percent of rated torque — rw
inline constexpr ObjectAddress<int16_t> kCommutationOffsetAppliedPercentOfRatedTorque{0x2009, 0x02};

/// Commutation offset / Measurement method — rw
inline constexpr ObjectAddress<int8_t> kCommutationOffsetMeasurementMethod{0x2009, 0x03};

/// Commutation offset / Phasing controller Kp — rw
inline constexpr ObjectAddress<float> kCommutationOffsetPhasingControllerKp{0x2009, 0x04};

/// Commutation offset / Phasing controller Ki — rw
inline constexpr ObjectAddress<float> kCommutationOffsetPhasingControllerKi{0x2009, 0x05};

/// Commutation offset / Phasing controller Kd — rw
inline constexpr ObjectAddress<float> kCommutationOffsetPhasingControllerKd{0x2009, 0x06};

/// I2t and Stall protection / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kI2tAndStallProtectionCount{0x200A, 0x00};

/// I2t and Stall protection / Enabled — rw
inline constexpr ObjectAddress<uint8_t> kI2tAndStallProtectionEnabled{0x200A, 0x01};

/// I2t and Stall protection / Peak time — rw, ms
inline constexpr ObjectAddress<uint32_t> kI2tAndStallProtectionPeakTime{0x200A, 0x02};

/// I2t and Stall protection / Motor heat index — ro
inline constexpr ObjectAddress<uint8_t> kI2tAndStallProtectionMotorHeatIndex{0x200A, 0x03};

/// I2t and Stall protection / Protection active — ro
inline constexpr ObjectAddress<uint8_t> kI2tAndStallProtectionProtectionActive{0x200A, 0x04};

/// I2t and Stall protection / Motor winding type — rw
inline constexpr ObjectAddress<uint8_t> kI2tAndStallProtectionMotorWindingType{0x200A, 0x05};

/// Max power — rw, W
inline constexpr ObjectAddress<uint32_t> kMaxPower{0x200B, 0x00};

/// Overspeed protection limit — rw
inline constexpr ObjectAddress<uint8_t> kOverspeedProtectionLimit{0x200C, 0x00};

/// System polarity — rw
inline constexpr ObjectAddress<uint8_t> kSystemPolarity{0x200D, 0x00};

/// Logging / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kLoggingCount{0x200E, 0x00};

/// Logging / State — rw
inline constexpr ObjectAddress<uint8_t> kLoggingState{0x200E, 0x01};

/// Torque controller / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTorqueControllerCount{0x2010, 0x00};

/// Torque controller / Controller Kp (disabled) — rw
inline constexpr ObjectAddress<float> kTorqueControllerControllerKpDisabled{0x2010, 0x01};

/// Torque controller / Controller Ki (disabled) — rw
inline constexpr ObjectAddress<float> kTorqueControllerControllerKiDisabled{0x2010, 0x02};

/// Torque controller / Controller Kd (disabled) — rw
inline constexpr ObjectAddress<float> kTorqueControllerControllerKdDisabled{0x2010, 0x03};

/// Torque controller / Field weakening enabled — rw
inline constexpr ObjectAddress<uint32_t> kTorqueControllerFieldWeakeningEnabled{0x2010, 0x04};

/// Torque controller / Field weakening percentage — rw
inline constexpr ObjectAddress<uint32_t> kTorqueControllerFieldWeakeningPercentage{0x2010, 0x05};

/// Torque controller / Field weakening starting speed (deprecated) — rw, rpm
inline constexpr ObjectAddress<uint32_t> kTorqueControllerFieldWeakeningStartingSpeedDeprecated{
    0x2010, 0x06};

/// Torque controller / Field weakening ending speed (deprecated) — rw, rpm
inline constexpr ObjectAddress<uint32_t> kTorqueControllerFieldWeakeningEndingSpeedDeprecated{
    0x2010, 0x07};

/// Torque controller / Commutation angle measurement delay — rw, μs
inline constexpr ObjectAddress<uint32_t> kTorqueControllerCommutationAngleMeasurementDelay{0x2010,
                                                                                           0x08};

/// Torque controller / Switching frequency — rw
inline constexpr ObjectAddress<uint8_t> kTorqueControllerSwitchingFrequency{0x2010, 0x09};

/// Torque controller / Settling time — rw, μs
inline constexpr ObjectAddress<uint16_t> kTorqueControllerSettlingTime{0x2010, 0x0A};

/// Torque controller / Damping ratio — rw
inline constexpr ObjectAddress<uint16_t> kTorqueControllerDampingRatio{0x2010, 0x0B};

/// Torque controller / Encoder source — rw
inline constexpr ObjectAddress<uint8_t> kTorqueControllerEncoderSource{0x2010, 0x0C};

/// Torque controller / Virtual Braking Chopper Enabled — rw
inline constexpr ObjectAddress<uint8_t> kTorqueControllerVirtualBrakingChopperEnabled{0x2010, 0x0D};

/// Torque controller / Virtual Braking Chopper Gain — rw
inline constexpr ObjectAddress<uint32_t> kTorqueControllerVirtualBrakingChopperGain{0x2010, 0x0E};

/// Torque controller / Virtual Braking Chopper Voltage Level — rw, mV
inline constexpr ObjectAddress<uint32_t> kTorqueControllerVirtualBrakingChopperVoltageLevel{0x2010,
                                                                                            0x0F};

/// Torque controller / MTPA Enabled — rw
inline constexpr ObjectAddress<uint8_t> kTorqueControllerMTPAEnabled{0x2010, 0x10};

/// Torque controller / Virtual Braking Chopper Notification Level — rw
inline constexpr ObjectAddress<uint8_t> kTorqueControllerVirtualBrakingChopperNotificationLevel{
    0x2010, 0x11};

/// Torque controller / Active short circuit duration time — rw, ms
inline constexpr ObjectAddress<uint32_t> kTorqueControllerActiveShortCircuitDurationTime{0x2010,
                                                                                         0x12};

/// Velocity controller / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kVelocityControllerCount{0x2011, 0x00};

/// Velocity controller / Controller Kp — rw
inline constexpr ObjectAddress<float> kVelocityControllerControllerKp{0x2011, 0x01};

/// Velocity controller / Controller Ki — rw
inline constexpr ObjectAddress<float> kVelocityControllerControllerKi{0x2011, 0x02};

/// Velocity controller / Controller Kd — rw
inline constexpr ObjectAddress<float> kVelocityControllerControllerKd{0x2011, 0x03};

/// Velocity controller / Controller integral limit — rw, mNm
inline constexpr ObjectAddress<uint32_t> kVelocityControllerControllerIntegralLimit{0x2011, 0x04};

/// Velocity controller / Encoder source — rw
inline constexpr ObjectAddress<uint8_t> kVelocityControllerEncoderSource{0x2011, 0x05};

/// Position controller / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kPositionControllerCount{0x2012, 0x00};

/// Position controller / Position loop Kp — rw
inline constexpr ObjectAddress<float> kPositionControllerPositionLoopKp{0x2012, 0x01};

/// Position controller / Position loop Ki — rw
inline constexpr ObjectAddress<float> kPositionControllerPositionLoopKi{0x2012, 0x02};

/// Position controller / Position loop Kd — rw
inline constexpr ObjectAddress<float> kPositionControllerPositionLoopKd{0x2012, 0x03};

/// Position controller / Position loop integral limit — rw, rpm
inline constexpr ObjectAddress<uint32_t> kPositionControllerPositionLoopIntegralLimit{0x2012, 0x04};

/// Position controller / Velocity loop Kp — rw
inline constexpr ObjectAddress<float> kPositionControllerVelocityLoopKp{0x2012, 0x05};

/// Position controller / Velocity loop Ki — rw
inline constexpr ObjectAddress<float> kPositionControllerVelocityLoopKi{0x2012, 0x06};

/// Position controller / Velocity loop Kd — rw
inline constexpr ObjectAddress<float> kPositionControllerVelocityLoopKd{0x2012, 0x07};

/// Position controller / Velocity loop integral limit — rw, mNm
inline constexpr ObjectAddress<uint32_t> kPositionControllerVelocityLoopIntegralLimit{0x2012, 0x08};

/// Position controller / Encoder source — rw
inline constexpr ObjectAddress<uint8_t> kPositionControllerEncoderSource{0x2012, 0x09};

/// Gain scheduling / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGainSchedulingCount{0x2013, 0x00};

/// Gain scheduling / Enabled — rw
inline constexpr ObjectAddress<uint8_t> kGainSchedulingEnabled{0x2013, 0x01};

/// Gain scheduling / Threshold velocity 0 — rw, rpm
inline constexpr ObjectAddress<uint32_t> kGainSchedulingThresholdVelocity0{0x2013, 0x02};

/// Gain scheduling / Position loop Kp 0 — rw
inline constexpr ObjectAddress<float> kGainSchedulingPositionLoopKp0{0x2013, 0x03};

/// Gain scheduling / Position loop Ki 0 — rw
inline constexpr ObjectAddress<float> kGainSchedulingPositionLoopKi0{0x2013, 0x04};

/// Gain scheduling / Position loop Kd 0 — rw
inline constexpr ObjectAddress<float> kGainSchedulingPositionLoopKd0{0x2013, 0x05};

/// Gain scheduling / Position loop integral limit 0 — rw, rpm
inline constexpr ObjectAddress<uint32_t> kGainSchedulingPositionLoopIntegralLimit0{0x2013, 0x06};

/// Gain scheduling / Velocity loop Kp 0 — rw
inline constexpr ObjectAddress<float> kGainSchedulingVelocityLoopKp0{0x2013, 0x07};

/// Gain scheduling / Velocity loop Ki 0 — rw
inline constexpr ObjectAddress<float> kGainSchedulingVelocityLoopKi0{0x2013, 0x08};

/// Gain scheduling / Velocity loop Kd 0 — rw
inline constexpr ObjectAddress<float> kGainSchedulingVelocityLoopKd0{0x2013, 0x09};

/// Gain scheduling / Velocity loop integral limit 0 — rw, mNm
inline constexpr ObjectAddress<uint32_t> kGainSchedulingVelocityLoopIntegralLimit0{0x2013, 0x0A};

/// Gain scheduling / Threshold velocity 1 — rw, rpm
inline constexpr ObjectAddress<uint32_t> kGainSchedulingThresholdVelocity1{0x2013, 0x0B};

/// Gain scheduling / Position loop Kp 1 — rw
inline constexpr ObjectAddress<float> kGainSchedulingPositionLoopKp1{0x2013, 0x0C};

/// Gain scheduling / Position loop Ki 1 — rw
inline constexpr ObjectAddress<float> kGainSchedulingPositionLoopKi1{0x2013, 0x0D};

/// Gain scheduling / Position loop Kd 1 — rw
inline constexpr ObjectAddress<float> kGainSchedulingPositionLoopKd1{0x2013, 0x0E};

/// Gain scheduling / Position loop integral limit 1 — rw, rpm
inline constexpr ObjectAddress<uint32_t> kGainSchedulingPositionLoopIntegralLimit1{0x2013, 0x0F};

/// Gain scheduling / Velocity loop Kp 1 — rw
inline constexpr ObjectAddress<float> kGainSchedulingVelocityLoopKp1{0x2013, 0x10};

/// Gain scheduling / Velocity loop Ki 1 — rw
inline constexpr ObjectAddress<float> kGainSchedulingVelocityLoopKi1{0x2013, 0x11};

/// Gain scheduling / Velocity loop Kd 1 — rw
inline constexpr ObjectAddress<float> kGainSchedulingVelocityLoopKd1{0x2013, 0x12};

/// Gain scheduling / Velocity loop integral limit 1 — rw, mNm
inline constexpr ObjectAddress<uint32_t> kGainSchedulingVelocityLoopIntegralLimit1{0x2013, 0x13};

/// Torque window / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTorqueWindowCount{0x2014, 0x00};

/// Torque window / Value — rw
inline constexpr ObjectAddress<uint16_t> kTorqueWindowValue{0x2014, 0x01};

/// Torque window / Time — rw, ms
inline constexpr ObjectAddress<uint16_t> kTorqueWindowTime{0x2014, 0x02};

/// Velocity feed forward / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kVelocityFeedForwardCount{0x2015, 0x00};

/// Velocity feed forward / Gain — rw
inline constexpr ObjectAddress<int16_t> kVelocityFeedForwardGain{0x2015, 0x01};

/// Velocity feed forward / Cutoff frequency — rw, Hz
inline constexpr ObjectAddress<uint16_t> kVelocityFeedForwardCutoffFrequency{0x2015, 0x02};

/// Following error option codes / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kFollowingErrorOptionCodesCount{0x2017, 0x00};

/// Following error option codes / Position following error option code — rw
inline constexpr ObjectAddress<uint8_t> kFollowingErrorOptionCodesPositionFollowingErrorOptionCode{
    0x2017, 0x01};

/// Following error option codes / Velocity following error option code — rw
inline constexpr ObjectAddress<uint8_t> kFollowingErrorOptionCodesVelocityFollowingErrorOptionCode{
    0x2017, 0x02};

/// Velocity following error / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kVelocityFollowingErrorCount{0x2018, 0x00};

/// Velocity following error / Window — rw, rpm
inline constexpr ObjectAddress<uint16_t> kVelocityFollowingErrorWindow{0x2018, 0x01};

/// Velocity following error / Time out — rw, ms
inline constexpr ObjectAddress<uint16_t> kVelocityFollowingErrorTimeOut{0x2018, 0x02};

/// Velocity following error / Actual value — ro, rpm
inline constexpr ObjectAddress<int32_t> kVelocityFollowingErrorActualValue{0x2018, 0x03};

/// Total motor current — ro
inline constexpr ObjectAddress<int16_t> kTotalMotorCurrent{0x2019, 0x00};

/// Velocity feedback filter / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kVelocityFeedbackFilterCount{0x2021, 0x00};

/// Velocity feedback filter / Type — rw
inline constexpr ObjectAddress<uint8_t> kVelocityFeedbackFilterType{0x2021, 0x01};

/// Velocity feedback filter / Cutoff frequency — rw, Hz
inline constexpr ObjectAddress<uint32_t> kVelocityFeedbackFilterCutoffFrequency{0x2021, 0x02};

/// Position feedback filter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kPositionFeedbackFilterCount{0x2022, 0x00};

/// Position feedback filter / Type — rw
inline constexpr ObjectAddress<uint8_t> kPositionFeedbackFilterType{0x2022, 0x01};

/// Position feedback filter / Cutoff frequency — rw, Hz
inline constexpr ObjectAddress<uint32_t> kPositionFeedbackFilterCutoffFrequency{0x2022, 0x02};

/// Notch filter / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kNotchFilterCount{0x2023, 0x00};

/// Notch filter / Enabled — rw
inline constexpr ObjectAddress<uint8_t> kNotchFilterEnabled{0x2023, 0x01};

/// Notch filter / Center frequency — rw, Hz
inline constexpr ObjectAddress<uint16_t> kNotchFilterCenterFrequency{0x2023, 0x02};

/// Notch filter / Rejection band — rw, Hz
inline constexpr ObjectAddress<uint16_t> kNotchFilterRejectionBand{0x2023, 0x03};

/// Notch filter / Depth — rw
inline constexpr ObjectAddress<uint16_t> kNotchFilterDepth{0x2023, 0x04};

/// Control input FIR filter / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kControlInputFIRFilterCount{0x2027, 0x00};

/// Control input FIR filter / Enabled — rw
inline constexpr ObjectAddress<uint8_t> kControlInputFIRFilterEnabled{0x2027, 0x01};

/// Control input FIR filter / Order — rw
inline constexpr ObjectAddress<uint16_t> kControlInputFIRFilterOrder{0x2027, 0x02};

/// Core temperature / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kCoreTemperatureCount{0x2030, 0x00};

/// Core temperature / Measured temperature — ro, m°C
inline constexpr ObjectAddress<int32_t> kCoreTemperatureMeasuredTemperature{0x2030, 0x01};

/// Drive temperature / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kDriveTemperatureCount{0x2031, 0x00};

/// Drive temperature / Measured temperature — ro, m°C
inline constexpr ObjectAddress<int32_t> kDriveTemperatureMeasuredTemperature{0x2031, 0x01};

/// External scaled measurement / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kExternalScaledMeasurementCount{0x2038, 0x00};

/// External scaled measurement / Scaled measurement value — ro
inline constexpr ObjectAddress<float> kExternalScaledMeasurementScaledMeasurementValue{0x2038,
                                                                                       0x01};

/// External scaled measurement / Analog input — rw
inline constexpr ObjectAddress<uint8_t> kExternalScaledMeasurementAnalogInput{0x2038, 0x02};

/// External scaled measurement / Resistance — rw, Ω
inline constexpr ObjectAddress<uint32_t> kExternalScaledMeasurementResistance{0x2038, 0x03};

/// External scaled measurement / Constant a0 — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementConstantA0{0x2038, 0x04};

/// External scaled measurement / Constant a1 — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementConstantA1{0x2038, 0x05};

/// External scaled measurement / Constant a2 — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementConstantA2{0x2038, 0x06};

/// External scaled measurement / Constant a3 — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementConstantA3{0x2038, 0x07};

/// External scaled measurement / Constant a4 — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementConstantA4{0x2038, 0x08};

/// External scaled measurement / Constant a5 — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementConstantA5{0x2038, 0x09};

/// External scaled measurement / Cutoff frequency — rw, Hz
inline constexpr ObjectAddress<uint16_t> kExternalScaledMeasurementCutoffFrequency{0x2038, 0x0A};

/// External scaled measurement / Upper error threshold — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementUpperErrorThreshold{0x2038, 0x0B};

/// External scaled measurement / Lower error threshold — rw
inline constexpr ObjectAddress<float> kExternalScaledMeasurementLowerErrorThreshold{0x2038, 0x0C};

/// Error report / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kErrorReportCount{0x203F, 0x00};

/// Error report / Description — ro
inline constexpr ObjectAddress<std::string> kErrorReportDescription{0x203F, 0x01};

/// Input counter — ro, Inc
inline constexpr ObjectAddress<uint32_t> kInputCounter{0x2040, 0x00};

/// Motor current / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kMotorCurrentCount{0x2041, 0x00};

/// Motor current / Vector amplitude — ro, mA
inline constexpr ObjectAddress<int32_t> kMotorCurrentVectorAmplitude{0x2041, 0x01};

/// Motor current / Phase advance angle — ro, mrad
inline constexpr ObjectAddress<int32_t> kMotorCurrentPhaseAdvanceAngle{0x2041, 0x02};

/// Joint torque controller / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kJointTorqueControllerCount{0x2050, 0x00};

/// Joint torque controller / Controller Kp — rw
inline constexpr ObjectAddress<float> kJointTorqueControllerControllerKp{0x2050, 0x01};

/// Joint torque controller / Controller Ki — rw
inline constexpr ObjectAddress<float> kJointTorqueControllerControllerKi{0x2050, 0x02};

/// Joint torque controller / Controller Kd — rw
inline constexpr ObjectAddress<float> kJointTorqueControllerControllerKd{0x2050, 0x03};

/// Joint torque controller / Controller integral limit — rw
inline constexpr ObjectAddress<uint32_t> kJointTorqueControllerControllerIntegralLimit{0x2050,
                                                                                       0x04};

/// Target joint torque — rw, mNm
inline constexpr ObjectAddress<int32_t> kTargetJointTorque{0x2051, 0x00};

/// Joint torque demand value — ro, mNm
inline constexpr ObjectAddress<int32_t> kJointTorqueDemandValue{0x2052, 0x00};

/// Joint torque offset — rw, mNm
inline constexpr ObjectAddress<int32_t> kJointTorqueOffset{0x2053, 0x00};

/// Max joint torque — rw, mNm
inline constexpr ObjectAddress<uint32_t> kMaxJointTorque{0x2054, 0x00};

/// Impedance controller / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kImpedanceControllerCount{0x2060, 0x00};

/// Impedance controller / Stiffness — rw, mNm/rad
inline constexpr ObjectAddress<int32_t> kImpedanceControllerStiffness{0x2060, 0x01};

/// Impedance controller / Damping — rw
inline constexpr ObjectAddress<int32_t> kImpedanceControllerDamping{0x2060, 0x02};

/// Impedance controller / Joint torque controller Kp — rw
inline constexpr ObjectAddress<float> kImpedanceControllerJointTorqueControllerKp{0x2060, 0x03};

/// Impedance controller / Joint torque controller Ki — rw
inline constexpr ObjectAddress<float> kImpedanceControllerJointTorqueControllerKi{0x2060, 0x04};

/// Impedance controller / Joint torque controller Kd — rw
inline constexpr ObjectAddress<float> kImpedanceControllerJointTorqueControllerKd{0x2060, 0x05};

/// Impedance controller / Joint torque controller integral limit — rw, mNm
inline constexpr ObjectAddress<uint32_t> kImpedanceControllerJointTorqueControllerIntegralLimit{
    0x2060, 0x06};

/// High resolution data / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kHighResolutionDataCount{0x20E1, 0x00};

/// High resolution data / SubIndex 001 — ro
inline constexpr ObjectAddress<std::vector<uint8_t>> kHighResolutionDataSubIndex001{0x20E1, 0x01};

/// High resolution data / SubIndex 002 — ro
inline constexpr ObjectAddress<std::vector<uint8_t>> kHighResolutionDataSubIndex002{0x20E1, 0x02};

/// High resolution data / SubIndex 003 — ro
inline constexpr ObjectAddress<std::vector<uint8_t>> kHighResolutionDataSubIndex003{0x20E1, 0x03};

/// High resolution data / SubIndex 004 — ro
inline constexpr ObjectAddress<std::vector<uint8_t>> kHighResolutionDataSubIndex004{0x20E1, 0x04};

/// Timestamp — ro, μs
inline constexpr ObjectAddress<uint32_t> kTimestamp{0x20F0, 0x00};

/// Assigned name — rw
inline constexpr ObjectAddress<std::string> kAssignedName{0x20F2, 0x00};

/// Encoder 1 configuration / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationCount{0x2110, 0x00};

/// Encoder 1 configuration / Sensor port — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationSensorPort{0x2110, 0x01};

/// Encoder 1 configuration / Type — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationType{0x2110, 0x02};

/// Encoder 1 configuration / Resolution — rw, Inc/Revolution
inline constexpr ObjectAddress<uint32_t> kEncoder1ConfigurationResolution{0x2110, 0x03};

/// Encoder 1 configuration / Zero velocity threshold — rw, μs
inline constexpr ObjectAddress<uint32_t> kEncoder1ConfigurationZeroVelocityThreshold{0x2110, 0x04};

/// Encoder 1 configuration / Polarity — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationPolarity{0x2110, 0x05};

/// Encoder 1 configuration / Singleturn offset — rw, Inc
inline constexpr ObjectAddress<uint32_t> kEncoder1ConfigurationSingleturnOffset{0x2110, 0x06};

/// Encoder 1 configuration / Access signal type — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationAccessSignalType{0x2110, 0x07};

/// Encoder 1 configuration / Clock frequency — rw, kHz
inline constexpr ObjectAddress<uint16_t> kEncoder1ConfigurationClockFrequency{0x2110, 0x08};

/// Encoder 1 configuration / Frame size — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationFrameSize{0x2110, 0x09};

/// Encoder 1 configuration / Multiturn bits — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationMultiturnBits{0x2110, 0x0A};

/// Encoder 1 configuration / Multiturn first bit position — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationMultiturnFirstBitPosition{0x2110,
                                                                                        0x0B};

/// Encoder 1 configuration / Singleturn bits — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationSingleturnBits{0x2110, 0x0C};

/// Encoder 1 configuration / Singleturn first bit position — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationSingleturnFirstBitPosition{0x2110,
                                                                                         0x0D};

/// Encoder 1 configuration / Timeout — rw, μs
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationTimeout{0x2110, 0x0E};

/// Encoder 1 configuration / CRC polynomial — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationCRCPolynomial{0x2110, 0x0F};

/// Encoder 1 configuration / Maximum tbusy — rw, μs
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationMaximumTbusy{0x2110, 0x10};

/// Encoder 1 configuration / Status bits active value — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationStatusBitsActiveValue{0x2110, 0x11};

/// Encoder 1 configuration / Parity type — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationParityType{0x2110, 0x12};

/// Encoder 1 configuration / First clock delay — rw, μs
inline constexpr ObjectAddress<uint16_t> kEncoder1ConfigurationFirstClockDelay{0x2110, 0x13};

/// Encoder 1 configuration / Data ordering — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationDataOrdering{0x2110, 0x14};

/// Encoder 1 configuration / Endianness — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationEndianness{0x2110, 0x15};

/// Encoder 1 configuration / Index availability — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationIndexAvailability{0x2110, 0x16};

/// Encoder 1 configuration / Hall sensor port — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationHallSensorPort{0x2110, 0x17};

/// Encoder 1 configuration / Sinewave cycles per revolution — rw
inline constexpr ObjectAddress<uint16_t> kEncoder1ConfigurationSinewaveCyclesPerRevolution{0x2110,
                                                                                           0x18};

/// Encoder 1 configuration / Sinewave resolution — rw, Inc
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationSinewaveResolution{0x2110, 0x19};

/// Encoder 1 configuration / Sinusoidal output voltage — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationSinusoidalOutputVoltage{0x2110, 0x1A};

/// Encoder 1 configuration / Filter (disabled) — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationFilterDisabled{0x2110, 0x1B};

/// Encoder 1 configuration / Sampling frequency — rw
inline constexpr ObjectAddress<uint8_t> kEncoder1ConfigurationSamplingFrequency{0x2110, 0x1C};

/// Encoder 1 feedback / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kEncoder1FeedbackCount{0x2111, 0x00};

/// Encoder 1 feedback / Raw position — ro, Inc
inline constexpr ObjectAddress<uint32_t> kEncoder1FeedbackRawPosition{0x2111, 0x01};

/// Encoder 1 feedback / Adjusted position — ro, Inc
inline constexpr ObjectAddress<int32_t> kEncoder1FeedbackAdjustedPosition{0x2111, 0x02};

/// Encoder 1 feedback / Velocity — ro, rpm
inline constexpr ObjectAddress<int32_t> kEncoder1FeedbackVelocity{0x2111, 0x03};

/// Encoder 1 feedback / Encoder status — ro
inline constexpr ObjectAddress<uint32_t> kEncoder1FeedbackEncoderStatus{0x2111, 0x04};

/// Encoder 2 configuration / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationCount{0x2112, 0x00};

/// Encoder 2 configuration / Sensor port — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationSensorPort{0x2112, 0x01};

/// Encoder 2 configuration / Type — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationType{0x2112, 0x02};

/// Encoder 2 configuration / Resolution — rw, Inc/Revolution
inline constexpr ObjectAddress<uint32_t> kEncoder2ConfigurationResolution{0x2112, 0x03};

/// Encoder 2 configuration / Zero velocity threshold — rw, μs
inline constexpr ObjectAddress<uint32_t> kEncoder2ConfigurationZeroVelocityThreshold{0x2112, 0x04};

/// Encoder 2 configuration / Polarity — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationPolarity{0x2112, 0x05};

/// Encoder 2 configuration / Singleturn offset — rw, Inc
inline constexpr ObjectAddress<uint32_t> kEncoder2ConfigurationSingleturnOffset{0x2112, 0x06};

/// Encoder 2 configuration / Access signal type — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationAccessSignalType{0x2112, 0x07};

/// Encoder 2 configuration / Clock frequency — rw, kHz
inline constexpr ObjectAddress<uint16_t> kEncoder2ConfigurationClockFrequency{0x2112, 0x08};

/// Encoder 2 configuration / Frame size — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationFrameSize{0x2112, 0x09};

/// Encoder 2 configuration / Multiturn bits — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationMultiturnBits{0x2112, 0x0A};

/// Encoder 2 configuration / Multiturn first bit position — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationMultiturnFirstBitPosition{0x2112,
                                                                                        0x0B};

/// Encoder 2 configuration / Singleturn bits — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationSingleturnBits{0x2112, 0x0C};

/// Encoder 2 configuration / Singleturn first bit position — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationSingleturnFirstBitPosition{0x2112,
                                                                                         0x0D};

/// Encoder 2 configuration / Timeout — rw, μs
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationTimeout{0x2112, 0x0E};

/// Encoder 2 configuration / CRC polynomial — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationCRCPolynomial{0x2112, 0x0F};

/// Encoder 2 configuration / Maximum tbusy — rw, μs
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationMaximumTbusy{0x2112, 0x10};

/// Encoder 2 configuration / Status bits active value — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationStatusBitsActiveValue{0x2112, 0x11};

/// Encoder 2 configuration / Parity type — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationParityType{0x2112, 0x12};

/// Encoder 2 configuration / First clock delay — rw, μs
inline constexpr ObjectAddress<uint16_t> kEncoder2ConfigurationFirstClockDelay{0x2112, 0x13};

/// Encoder 2 configuration / Data ordering — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationDataOrdering{0x2112, 0x14};

/// Encoder 2 configuration / Endianness — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationEndianness{0x2112, 0x15};

/// Encoder 2 configuration / Index availability — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationIndexAvailability{0x2112, 0x16};

/// Encoder 2 configuration / Hall sensor port — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationHallSensorPort{0x2112, 0x17};

/// Encoder 2 configuration / Sinewave cycles per revolution — rw
inline constexpr ObjectAddress<uint16_t> kEncoder2ConfigurationSinewaveCyclesPerRevolution{0x2112,
                                                                                           0x18};

/// Encoder 2 configuration / Sinewave resolution — rw, Inc
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationSinewaveResolution{0x2112, 0x19};

/// Encoder 2 configuration / Sinusoidal output voltage — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationSinusoidalOutputVoltage{0x2112, 0x1A};

/// Encoder 2 configuration / Filter (disabled) — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationFilterDisabled{0x2112, 0x1B};

/// Encoder 2 configuration / Sampling frequency — rw
inline constexpr ObjectAddress<uint8_t> kEncoder2ConfigurationSamplingFrequency{0x2112, 0x1C};

/// Encoder 2 feedback / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kEncoder2FeedbackCount{0x2113, 0x00};

/// Encoder 2 feedback / Raw position — ro, Inc
inline constexpr ObjectAddress<uint32_t> kEncoder2FeedbackRawPosition{0x2113, 0x01};

/// Encoder 2 feedback / Adjusted position — ro, Inc
inline constexpr ObjectAddress<int32_t> kEncoder2FeedbackAdjustedPosition{0x2113, 0x02};

/// Encoder 2 feedback / Velocity — ro, rpm
inline constexpr ObjectAddress<int32_t> kEncoder2FeedbackVelocity{0x2113, 0x03};

/// Encoder 2 feedback / Encoder status — ro
inline constexpr ObjectAddress<uint32_t> kEncoder2FeedbackEncoderStatus{0x2113, 0x04};

/// Torque sensor configuration / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTorqueSensorConfigurationCount{0x2150, 0x00};

/// Torque sensor configuration / Type — rw
inline constexpr ObjectAddress<uint8_t> kTorqueSensorConfigurationType{0x2150, 0x01};

/// Torque sensor configuration / Polarity — rw
inline constexpr ObjectAddress<uint8_t> kTorqueSensorConfigurationPolarity{0x2150, 0x02};

/// Torque sensor configuration / Channel — rw
inline constexpr ObjectAddress<uint8_t> kTorqueSensorConfigurationChannel{0x2150, 0x03};

/// Torque sensor configuration / Gain — rw
inline constexpr ObjectAddress<float> kTorqueSensorConfigurationGain{0x2150, 0x04};

/// Torque sensor configuration / Offset — rw, mNm
inline constexpr ObjectAddress<int32_t> kTorqueSensorConfigurationOffset{0x2150, 0x05};

/// Torque sensor configuration / Coefficient K1 — rw
inline constexpr ObjectAddress<float> kTorqueSensorConfigurationCoefficientK1{0x2150, 0x06};

/// Torque sensor configuration / Coefficient K2 — rw
inline constexpr ObjectAddress<float> kTorqueSensorConfigurationCoefficientK2{0x2150, 0x07};

/// Torque sensor configuration / Coefficient K3 — rw
inline constexpr ObjectAddress<float> kTorqueSensorConfigurationCoefficientK3{0x2150, 0x08};

/// Torque sensor configuration / Coefficient K4 — rw
inline constexpr ObjectAddress<float> kTorqueSensorConfigurationCoefficientK4{0x2150, 0x09};

/// Torque sensor configuration / Coefficient K5 — rw
inline constexpr ObjectAddress<float> kTorqueSensorConfigurationCoefficientK5{0x2150, 0x0A};

/// Torque sensor value — ro, mNm
inline constexpr ObjectAddress<int32_t> kTorqueSensorValue{0x2151, 0x00};

/// Torque sensor feedback filter / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTorqueSensorFeedbackFilterCount{0x2152, 0x00};

/// Torque sensor feedback filter / Type — rw
inline constexpr ObjectAddress<uint8_t> kTorqueSensorFeedbackFilterType{0x2152, 0x01};

/// Torque sensor feedback filter / Cutoff frequency — rw, Hz
inline constexpr ObjectAddress<uint32_t> kTorqueSensorFeedbackFilterCutoffFrequency{0x2152, 0x02};

/// GPIO pin configuration / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationCount{0x2210, 0x00};

/// GPIO pin configuration / Digital IO 1 — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationDigitalIO1{0x2210, 0x01};

/// GPIO pin configuration / Digital IO 2 — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationDigitalIO2{0x2210, 0x02};

/// GPIO pin configuration / Digital IO 3 — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationDigitalIO3{0x2210, 0x03};

/// GPIO pin configuration / Digital IO 4 — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationDigitalIO4{0x2210, 0x04};

/// GPIO pin configuration / Digital IO 5 — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationDigitalIO5{0x2210, 0x05};

/// GPIO pin configuration / Digital IO 6 — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationDigitalIO6{0x2210, 0x06};

/// GPIO pin configuration / Digital IO 7 — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPinConfigurationDigitalIO7{0x2210, 0x07};

/// GPIO output events / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGPIOOutputEventsCount{0x2211, 0x00};

/// GPIO output events / Timestamp setpoint — rw
inline constexpr ObjectAddress<uint32_t> kGPIOOutputEventsTimestampSetpoint{0x2211, 0x01};

/// GPIO input actions / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGPIOInputActionsCount{0x2212, 0x00};

/// GPIO input actions / Timestamp on rising edge — ro
inline constexpr ObjectAddress<uint32_t> kGPIOInputActionsTimestampOnRisingEdge{0x2212, 0x01};

/// GPIO position trigger / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGPIOPositionTriggerCount{0x2213, 0x00};

/// GPIO position trigger / Position setpoint — rw, Inc
inline constexpr ObjectAddress<int32_t> kGPIOPositionTriggerPositionSetpoint{0x2213, 0x01};

/// GPIO position trigger / Target encoder — rw
inline constexpr ObjectAddress<uint8_t> kGPIOPositionTriggerTargetEncoder{0x2213, 0x02};

/// GPIO position trigger / Pulse width — rw, ms
inline constexpr ObjectAddress<uint8_t> kGPIOPositionTriggerPulseWidth{0x2213, 0x03};

/// GPIO global options / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGPIOGlobalOptionsCount{0x2214, 0x00};

/// GPIO global options / Voltage level — rw
inline constexpr ObjectAddress<uint8_t> kGPIOGlobalOptionsVoltageLevel{0x2214, 0x01};

/// GPIO addressable LED control / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGPIOAddressableLEDControlCount{0x2215, 0x00};

/// GPIO addressable LED control / LED color — rw
inline constexpr ObjectAddress<uint32_t> kGPIOAddressableLEDControlLEDColor{0x2215, 0x01};

/// Analog input 1 — ro
inline constexpr ObjectAddress<uint16_t> kAnalogInput1{0x2401, 0x00};

/// Analog input 2 — ro
inline constexpr ObjectAddress<uint16_t> kAnalogInput2{0x2402, 0x00};

/// Analog input 3 — ro
inline constexpr ObjectAddress<uint16_t> kAnalogInput3{0x2403, 0x00};

/// Analog input 4 — ro
inline constexpr ObjectAddress<uint16_t> kAnalogInput4{0x2404, 0x00};

/// Cyclic control input frequency — rw
inline constexpr ObjectAddress<uint8_t> kCyclicControlInputFrequency{0x2500, 0x00};

/// Temperature warning — ro
inline constexpr ObjectAddress<uint8_t> kTemperatureWarning{0x2600, 0x00};

/// Safe position valid — ro
inline constexpr ObjectAddress<uint8_t> kSafePositionValid{0x2601, 0x00};

/// Safe speed valid — ro
inline constexpr ObjectAddress<uint8_t> kSafeSpeedValid{0x2602, 0x00};

/// Safe input / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafeInputCount{0x2603, 0x00};

/// Safe input / SubIndex 001 — ro
inline constexpr ObjectAddress<uint8_t> kSafeInputSubIndex001{0x2603, 0x01};

/// Safe input / SubIndex 002 — ro
inline constexpr ObjectAddress<uint8_t> kSafeInputSubIndex002{0x2603, 0x02};

/// Safe input / SubIndex 003 — ro
inline constexpr ObjectAddress<uint8_t> kSafeInputSubIndex003{0x2603, 0x03};

/// Safe input / SubIndex 004 — ro
inline constexpr ObjectAddress<uint8_t> kSafeInputSubIndex004{0x2603, 0x04};

/// Safe output monitor / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafeOutputMonitorCount{0x2604, 0x00};

/// Safe output monitor / SubIndex 001 — ro
inline constexpr ObjectAddress<uint8_t> kSafeOutputMonitorSubIndex001{0x2604, 0x01};

/// Safe output monitor / SubIndex 002 — ro
inline constexpr ObjectAddress<uint8_t> kSafeOutputMonitorSubIndex002{0x2604, 0x02};

/// Analog input / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kAnalogInputCount{0x2605, 0x00};

/// Analog input / Analog diagnostic active — rw
inline constexpr ObjectAddress<uint8_t> kAnalogInputAnalogDiagnosticActive{0x2605, 0x01};

/// Analog input / Analog value valid — ro
inline constexpr ObjectAddress<uint8_t> kAnalogInputAnalogValueValid{0x2605, 0x02};

/// Analog input / Safe analog value (scaled) — ro
inline constexpr ObjectAddress<int16_t> kAnalogInputSafeAnalogValueScaled{0x2605, 0x03};

/// Manufacturing parameters / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kManufacturingParametersCount{0x2610, 0x00};

/// Manufacturing parameters / Vendor ID — ro
inline constexpr ObjectAddress<uint32_t> kManufacturingParametersVendorID{0x2610, 0x01};

/// Manufacturing parameters / Device Type — ro
inline constexpr ObjectAddress<std::string> kManufacturingParametersDeviceType{0x2610, 0x02};

/// Manufacturing parameters / Device Version — ro
inline constexpr ObjectAddress<std::string> kManufacturingParametersDeviceVersion{0x2610, 0x03};

/// Manufacturing parameters / Serial Number — ro
inline constexpr ObjectAddress<std::string> kManufacturingParametersSerialNumber{0x2610, 0x04};

/// Safety Module input diagnostics / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyModuleInputDiagnosticsCount{0x2611, 0x00};

/// Safety Module input diagnostics / SubIndex 001 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyModuleInputDiagnosticsSubIndex001{0x2611, 0x01};

/// Safety Module input diagnostics / SubIndex 002 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyModuleInputDiagnosticsSubIndex002{0x2611, 0x02};

/// General / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kGeneralCount{0x2620, 0x00};

/// General / Drive safety name — rw
inline constexpr ObjectAddress<std::string> kGeneralDriveSafetyName{0x2620, 0x01};

/// General / Safe fieldbus — rw
inline constexpr ObjectAddress<uint8_t> kGeneralSafeFieldbus{0x2620, 0x02};

/// General / Safe address — rw
inline constexpr ObjectAddress<uint16_t> kGeneralSafeAddress{0x2620, 0x03};

/// General / FSoE Download — rw
inline constexpr ObjectAddress<uint8_t> kGeneralFSoEDownload{0x2620, 0x04};

/// Safety digital IO / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOCount{0x2621, 0x00};

/// Safety digital IO / Acknowledge via drive — rw
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOAcknowledgeViaDrive{0x2621, 0x01};

/// Safety digital IO / Acknowledgement input — rw
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOAcknowledgementInput{0x2621, 0x02};

/// Safety digital IO / Input test pulse detection — rw
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOInputTestPulseDetection{0x2621, 0x03};

/// Safety digital IO / Input filter time — rw, ms
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOInputFilterTime{0x2621, 0x04};

/// Safety digital IO / Test pulse max. distance — rw, ms
inline constexpr ObjectAddress<uint16_t> kSafetyDigitalIOTestPulseMaxDistance{0x2621, 0x05};

/// Safety digital IO / Output test pulse — rw
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOOutputTestPulse{0x2621, 0x06};

/// Safety digital IO / Output1 function — rw
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOOutput1Function{0x2621, 0x07};

/// Safety digital IO / Output2 function — rw
inline constexpr ObjectAddress<uint8_t> kSafetyDigitalIOOutput2Function{0x2621, 0x08};

/// Safety IO analog input / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafetyIOAnalogInputCount{0x2625, 0x00};

/// Safety IO analog input / Analog input1 Gain — rw, nNm/Inc
inline constexpr ObjectAddress<int32_t> kSafetyIOAnalogInputAnalogInput1Gain{0x2625, 0x01};

/// Safety IO analog input / Analog input1 Offset — rw, Inc
inline constexpr ObjectAddress<int16_t> kSafetyIOAnalogInputAnalogInput1Offset{0x2625, 0x02};

/// Safety IO analog input / Analog input2 Gain — rw, nNm/Inc
inline constexpr ObjectAddress<int32_t> kSafetyIOAnalogInputAnalogInput2Gain{0x2625, 0x03};

/// Safety IO analog input / Analog input2 Offset — rw, Inc
inline constexpr ObjectAddress<int16_t> kSafetyIOAnalogInputAnalogInput2Offset{0x2625, 0x04};

/// Safety IO analog input / Analog allowed error — rw, nNm
inline constexpr ObjectAddress<uint32_t> kSafetyIOAnalogInputAnalogAllowedError{0x2625, 0x05};

/// Safety IO analog input / Safe analog input filter time — rw, ms
inline constexpr ObjectAddress<uint8_t> kSafetyIOAnalogInputSafeAnalogInputFilterTime{0x2625, 0x06};

/// Safety IO analog input / Safe analog in channel A — ro
inline constexpr ObjectAddress<int16_t> kSafetyIOAnalogInputSafeAnalogInChannelA{0x2625, 0x07};

/// Safety IO analog input / Safe analog in channel B — ro
inline constexpr ObjectAddress<int16_t> kSafetyIOAnalogInputSafeAnalogInChannelB{0x2625, 0x08};

/// Encoder source type / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kEncoderSourceTypeCount{0x2630, 0x00};

/// Encoder source type — rw
inline constexpr ObjectAddress<uint8_t> kEncoderSourceType{0x2630, 0x01};

/// Encoder source type / Encoder resolution — rw, Inc
inline constexpr ObjectAddress<uint32_t> kEncoderSourceTypeEncoderResolution{0x2630, 0x02};

/// Encoder source type / Encoder multiturn bits — rw, Bit
inline constexpr ObjectAddress<uint8_t> kEncoderSourceTypeEncoderMultiturnBits{0x2630, 0x03};

/// Encoder source type / Encoder clock frequency — rw
inline constexpr ObjectAddress<uint8_t> kEncoderSourceTypeEncoderClockFrequency{0x2630, 0x04};

/// Encoder source type / Encoder timeout — rw, μs
inline constexpr ObjectAddress<uint16_t> kEncoderSourceTypeEncoderTimeout{0x2630, 0x05};

/// Encoder source type / Multiturn Counting by SMM — rw
inline constexpr ObjectAddress<uint8_t> kEncoderSourceTypeMultiturnCountingBySMM{0x2630, 0x06};

/// Encoder verification / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kEncoderVerificationCount{0x2631, 0x00};

/// Encoder verification / Verification sensor source type — rw
inline constexpr ObjectAddress<uint8_t> kEncoderVerificationVerificationSensorSourceType{0x2631,
                                                                                         0x01};

/// Encoder verification / Verification sensor resolution — rw, Inc
inline constexpr ObjectAddress<uint32_t> kEncoderVerificationVerificationSensorResolution{0x2631,
                                                                                          0x02};

/// Encoder verification / Verification sensor multiturn bits — rw, Bit
inline constexpr ObjectAddress<uint8_t> kEncoderVerificationVerificationSensorMultiturnBits{0x2631,
                                                                                            0x03};

/// Encoder selection / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kEncoderSelectionCount{0x2635, 0x00};

/// Encoder selection / Speed window — rw, ms
inline constexpr ObjectAddress<uint8_t> kEncoderSelectionSpeedWindow{0x2635, 0x01};

/// Encoder selection / Absolute position — rw
inline constexpr ObjectAddress<uint8_t> kEncoderSelectionAbsolutePosition{0x2635, 0x02};

/// Encoder selection / Position reset input — rw
inline constexpr ObjectAddress<uint8_t> kEncoderSelectionPositionResetInput{0x2635, 0x03};

/// Encoder selection / Absolute position on reset — rw
inline constexpr ObjectAddress<uint32_t> kEncoderSelectionAbsolutePositionOnReset{0x2635, 0x04};

/// Encoder selection / Allowed position discrepancy — rw
inline constexpr ObjectAddress<uint16_t> kEncoderSelectionAllowedPositionDiscrepancy{0x2635, 0x05};

/// Encoder selection / Allowed speed discrepancy — rw
inline constexpr ObjectAddress<uint16_t> kEncoderSelectionAllowedSpeedDiscrepancy{0x2635, 0x06};

/// Encoder selection / Discrepancy timer — rw, ms
inline constexpr ObjectAddress<uint16_t> kEncoderSelectionDiscrepancyTimer{0x2635, 0x07};

/// Encoder selection / Verification scaling numerator — rw
inline constexpr ObjectAddress<int16_t> kEncoderSelectionVerificationScalingNumerator{0x2635, 0x08};

/// Encoder selection / Verification scaling denominator — rw
inline constexpr ObjectAddress<uint16_t> kEncoderSelectionVerificationScalingDenominator{0x2635,
                                                                                         0x09};

/// Encoder selection / Primary encoder used for commutation — rw
inline constexpr ObjectAddress<uint8_t> kEncoderSelectionPrimaryEncoderUsedForCommutation{0x2635,
                                                                                          0x0A};

/// Encoder selection / System polarity (safety) — rw
inline constexpr ObjectAddress<uint8_t> kEncoderSelectionSystemPolaritySafety{0x2635, 0x0B};

/// Encoder selection / max. position discrepancy — ro
inline constexpr ObjectAddress<uint32_t> kEncoderSelectionMaxPositionDiscrepancy{0x2635, 0x0C};

/// STO input / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSTOInputCount{0x2641, 0x00};

/// STO input — rw
inline constexpr ObjectAddress<uint8_t> kSTOInput{0x2641, 0x01};

/// STO input / SBC — rw
inline constexpr ObjectAddress<uint8_t> kSTOInputSBC{0x2641, 0x02};

/// SS1 input / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSS1InputCount{0x2650, 0x00};

/// SS1 input — rw
inline constexpr ObjectAddress<uint8_t> kSS1Input{0x2650, 0x01};

/// SS1 input / SS1: Deceleration monitoring — rw
inline constexpr ObjectAddress<uint8_t> kSS1InputSS1DecelerationMonitoring{0x2650, 0x02};

/// SOS input / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSOSInputCount{0x2668, 0x00};

/// SOS input — rw
inline constexpr ObjectAddress<uint8_t> kSOSInput{0x2668, 0x01};

/// SOS input / t_D_SOS — rw, ms
inline constexpr ObjectAddress<uint16_t> kSOSInputTDSOS{0x2668, 0x02};

/// SS2 input / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSS2InputCount{0x2670, 0x00};

/// SS2 input — rw
inline constexpr ObjectAddress<uint8_t> kSS2Input{0x2670, 0x01};

/// SLS input / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSLSInputCount{0x2690, 0x00};

/// SLS input / SLS1 input — rw
inline constexpr ObjectAddress<uint8_t> kSLSInputSLS1Input{0x2690, 0x01};

/// SLS input / SLS2 input — rw
inline constexpr ObjectAddress<uint8_t> kSLSInputSLS2Input{0x2690, 0x02};

/// SLS input / SLS3 input — rw
inline constexpr ObjectAddress<uint8_t> kSLSInputSLS3Input{0x2690, 0x03};

/// SLS input / SLS4 input — rw
inline constexpr ObjectAddress<uint8_t> kSLSInputSLS4Input{0x2690, 0x04};

/// Reset position — rw
inline constexpr ObjectAddress<uint8_t> kResetPosition{0x26A0, 0x00};

/// Safe torque / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafeTorqueCount{0x26B0, 0x00};

/// Safe torque / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSafeTorqueSubIndex001{0x26B0, 0x01};

/// Safe torque / SubIndex 002 — rw
inline constexpr ObjectAddress<uint8_t> kSafeTorqueSubIndex002{0x26B0, 0x02};

/// Safe torque parameter / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafeTorqueParameterCount{0x26B1, 0x00};

/// Safe torque parameter / Torque constant (safety) — rw, μNm/A
inline constexpr ObjectAddress<uint32_t> kSafeTorqueParameterTorqueConstantSafety{0x26B1, 0x01};

/// Safe torque parameter / Safe torque filter time — rw, ms
inline constexpr ObjectAddress<uint8_t> kSafeTorqueParameterSafeTorqueFilterTime{0x26B1, 0x02};

/// Safe torque parameter / number of pole pairs — rw
inline constexpr ObjectAddress<uint8_t> kSafeTorqueParameterNumberOfPolePairs{0x26B1, 0x03};

/// Safe torque parameter / commutation angle offset (safety) — rw
inline constexpr ObjectAddress<int16_t> kSafeTorqueParameterCommutationAngleOffsetSafety{0x26B1,
                                                                                         0x04};

/// SLT input / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSLTInputCount{0x26B2, 0x00};

/// SLT input — rw
inline constexpr ObjectAddress<uint8_t> kSLTInput{0x26B2, 0x01};

/// SLT input / SLT source — rw
inline constexpr ObjectAddress<uint8_t> kSLTInputSLTSource{0x26B2, 0x02};

/// Safe output / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kSafeOutputCount{0x26F0, 0x00};

/// Safe output / SubIndex 001 — rw
inline constexpr ObjectAddress<uint8_t> kSafeOutputSubIndex001{0x26F0, 0x01};

/// Safe output / SubIndex 002 — rw
inline constexpr ObjectAddress<uint8_t> kSafeOutputSubIndex002{0x26F0, 0x02};

/// Firmware / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kFirmwareCount{0x2700, 0x00};

/// Firmware / Core version — ro
inline constexpr ObjectAddress<std::string> kFirmwareCoreVersion{0x2700, 0x01};

/// Tuning command — rw
inline constexpr ObjectAddress<uint32_t> kTuningCommand{0x2701, 0x00};

/// Tuning status — rw
inline constexpr ObjectAddress<uint32_t> kTuningStatus{0x2702, 0x00};

/// User MOSI — rw
inline constexpr ObjectAddress<uint32_t> kUserMOSI{0x2703, 0x00};

/// User MISO — rw
inline constexpr ObjectAddress<uint32_t> kUserMISO{0x2704, 0x00};

/// Setup wizard completed — rw
inline constexpr ObjectAddress<uint8_t> kSetupWizardCompleted{0x2705, 0x00};

/// TCP/IP Configuration / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kTCPIPConfigurationCount{0x2E00, 0x00};

/// TCP/IP Configuration / IP address — rw
inline constexpr ObjectAddress<uint32_t> kTCPIPConfigurationIPAddress{0x2E00, 0x01};

/// TCP/IP Configuration / Network mask — rw
inline constexpr ObjectAddress<uint32_t> kTCPIPConfigurationNetworkMask{0x2E00, 0x02};

/// TCP/IP Configuration / Gateway address — rw
inline constexpr ObjectAddress<uint32_t> kTCPIPConfigurationGatewayAddress{0x2E00, 0x03};

/// TCP/IP Configuration / Name server — rw
inline constexpr ObjectAddress<uint32_t> kTCPIPConfigurationNameServer{0x2E00, 0x04};

/// TCP/IP Configuration / Name server 2 — rw
inline constexpr ObjectAddress<uint32_t> kTCPIPConfigurationNameServer2{0x2E00, 0x05};

/// TCP/IP Configuration / Domain name — rw
inline constexpr ObjectAddress<std::string> kTCPIPConfigurationDomainName{0x2E00, 0x06};

/// TCP/IP Configuration / Host name — rw
inline constexpr ObjectAddress<std::string> kTCPIPConfigurationHostName{0x2E00, 0x07};

/// Internal usage only / SubIndex 000 — ro
inline constexpr ObjectAddress<uint8_t> kInternalUsageOnlyCount{0x2FFF, 0x00};

/// Internal usage only / TCTM3 — ro
inline constexpr ObjectAddress<int16_t> kInternalUsageOnlyTCTM3{0x2FFF, 0x01};

/// Internal usage only / TCTM4 — ro
inline constexpr ObjectAddress<int16_t> kInternalUsageOnlyTCTM4{0x2FFF, 0x02};

/// Internal usage only / TCNM1 — ro
inline constexpr ObjectAddress<int16_t> kInternalUsageOnlyTCNM1{0x2FFF, 0x03};

/// Internal usage only / BKC — ro
inline constexpr ObjectAddress<uint16_t> kInternalUsageOnlyBKC{0x2FFF, 0x04};

/// FSoE Communication Parameter / Number of Subindex — ro
inline constexpr ObjectAddress<uint8_t> kFSoECommunicationParameterCount{0xE901, 0x00};

/// FSoE Communication Parameter / Version — ro
inline constexpr ObjectAddress<std::string> kFSoECommunicationParameterVersion{0xE901, 0x01};

/// FSoE Communication Parameter / SafetyAddress — ro
inline constexpr ObjectAddress<uint16_t> kFSoECommunicationParameterSafetyAddress{0xE901, 0x02};

/// FSoE Communication Parameter / FSoE Connection ID — ro
inline constexpr ObjectAddress<uint16_t> kFSoECommunicationParameterFSoEConnectionID{0xE901, 0x03};

/// FSoE Communication Parameter / Watchdog Time — ro
inline constexpr ObjectAddress<uint16_t> kFSoECommunicationParameterWatchdogTime{0xE901, 0x04};

/// FSoE Communication Parameter / Unique Device ID — ro
inline constexpr ObjectAddress<std::vector<uint8_t>> kFSoECommunicationParameterUniqueDeviceID{
    0xE901, 0x05};

/// FSoE Communication Parameter / Connection Type — ro
inline constexpr ObjectAddress<uint16_t> kFSoECommunicationParameterConnectionType{0xE901, 0x06};

/// FSoE Communication Parameter / Communication Parameter Length — ro
inline constexpr ObjectAddress<uint16_t> kFSoECommunicationParameterCommunicationParameterLength{
    0xE901, 0x07};

/// FSoE Communication Parameter / Application Parameter Length — ro
inline constexpr ObjectAddress<uint16_t> kFSoECommunicationParameterApplicationParameterLength{
    0xE901, 0x08};

/// FSoE Communication Parameter / SRA CRC — ro
inline constexpr ObjectAddress<uint32_t> kFSoECommunicationParameterSRACRC{0xE901, 0x09};

/// Device Safety Address / Subindex 000 — ro
inline constexpr ObjectAddress<uint8_t> kDeviceSafetyAddressCount{0xF980, 0x00};

/// Device Safety Address / FSoE Address — ro
inline constexpr ObjectAddress<uint16_t> kDeviceSafetyAddressFSoEAddress{0xF980, 0x01};

}  // namespace mm::node::somanet::objects
