#pragma once

#include <string_view>

namespace mm {

/// The OpenAPI specification (`swagger.yml`) embedded into the binary at build time and served
/// verbatim at `GET /api/swagger.yml`. Lets a client fetch the exact contract of the running
/// server — no repo checkout or packaged file needed. Generated by cmake/embed_file.cmake.
extern const std::string_view kSwaggerYml;

}  // namespace mm
