#!/usr/bin/env bash
#
# Build a flashable Raspberry Pi 5 image: Debian 14 + PREEMPT_RT + Motion Master.
#
# Why this exists. The Pi cannot be provisioned the way the AAeon board is: the
# image ships no cloud-init and no sshd, and has no network configured, so there
# is nothing for Ansible to connect to until it has been booted and set up once.
# Everything therefore has to be in place before first boot.
#
# So the image is provisioned offline: boot its root filesystem in QEMU, run the
# same rt-target.yml playbook against it over SSH, shut down, and write the
# result to a microSD card. Same roles, same inventory shape, same everything —
# only the delivery differs.
#
# Two things are unlike rt/vm:
#   * QEMU has no Pi 5 machine type, so this boots a generic arm64 "virt" guest
#     using the kernel and initrd taken out of the image. The Pi's own firmware
#     boots the card for real; QEMU only has to run the userland long enough to
#     provision it.
#   * There is no KVM for arm64 on an x86 host, so it runs under TCG emulation.
#     Expect this to take a while. Iterate roles on the x86 VM (rt/vm), and come
#     here when you want an image.
#
# Usage: run it as yourself — NOT under sudo. It asks for your password once, up
# front, for the loop-mount and chroot steps; everything else is ordinary user
# work and running it as root only leaves root-owned files behind.
#
#   ./rt/image/build-rpi-image.sh
#
# Prerequisites (none of these is needed by anything else in rt/):
#   qemu-system-aarch64      not installed by default on a dev box
#   qemu-user-static         binfmt handler, so apt can run in the arm64 chroot
#   sudo rights              for loop-mount, mount and chroot only
#
# Getting into the finished card. Every image is built to be logged into, by a
# key that is meant to be shared and a password that is not a secret:
#
#   ssh -i ~/.ssh/motion-master-rpi root@<address>     (generated on first run)
#   console: root / root
#
# Neither is a weakness to be fixed later. The board's HTTP API is
# unauthenticated and binds every interface, so the credentials are not what
# stands between the drives and the network — the network's own trust boundary
# is. What they buy is a board that can be recovered when Ethernet does not come
# up, which is the failure this hardware has not yet been proven against.
# Override with RT_IMAGE_ACCESS_KEY and RT_IMAGE_ROOT_PASSWORD; setting the
# latter empty leaves root locked and the key the only way in.
#
# Where the base image comes from, and a trap worth knowing about.
#
# raspi.debian.net still serves two pages of "daily" and "tested" images that
# stop at Pi 4 and whose files now 404. Those builds are dead: that site's front
# page says the project "has been superseded by the images generated by the
# Debian Cloud Images", and its FAQ (which still says Pi 5 is unsupported) was
# not updated to match. The live images are official Debian cloud builds:
#
#   https://cloud.debian.org/images/cloud/forky/daily/latest/
#     debian-14-raspi-arm64-daily.tar.xz    (vendor: raspi, arch: arm64)
#
# Forky specifically — raspi.debian.net's front page states "RPi 5 only works
# with Debian 14 Forky (testing) or Sid", which matches stable shipping a 6.12
# kernel that predates usable RP1 support.
#
# The tarball contains a single member, disk.raw.

set -euo pipefail

IMAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_DIR="${RT_IMAGE_CACHE_DIR:-$IMAGE_DIR/.cache}"
ANSIBLE_DIR="$IMAGE_DIR/../provision/ansible"

BASE_URL="${RT_IMAGE_BASE_URL:-https://cloud.debian.org/images/cloud/forky/daily/latest}"
BASE_NAME="${RT_IMAGE_BASE_NAME:-debian-14-raspi-arm64-daily.tar.xz}"

# The tarball's single member is disk.raw, extracted under this name.
BASE_IMAGE="$CACHE_DIR/disk.raw"
WORK_IMAGE="$CACHE_DIR/motion-master-rpi5.img"
SSH_KEY="$CACHE_DIR/id_ed25519"
PID_FILE="$CACHE_DIR/qemu.pid"
SERIAL_LOG="$CACHE_DIR/serial.log"
MOUNT_DIR="$CACHE_DIR/mnt"

# This is build headroom, not the appliance's capacity: the growroot role grows
# the card to its real size on first boot, so this number only decides how much
# provisioning has to fit into and how many bytes dd has to write.
#
# A provisioned image uses about 2 GiB, so 8G is roughly four times what is
# needed today. That margin is deliberate — running out of space happens at the
# apt step of a two-hour emulated build, and a smaller image would have to be
# revisited every time a role installs something bulky. Writing the extra
# gigabytes costs a couple of minutes once per card; being wrong costs the whole
# build.
IMAGE_SIZE="${RT_IMAGE_SIZE:-8G}"
VM_CPUS="${RT_IMAGE_CPUS:-4}"
VM_MEMORY_MB="${RT_IMAGE_MEMORY_MB:-4096}"
SSH_HOST="127.0.0.1"
SSH_PORT="${RT_IMAGE_SSH_PORT:-2223}"
VM_USER="${RT_IMAGE_USER:-root}"
BOOT_TIMEOUT="${RT_IMAGE_BOOT_TIMEOUT:-900}"
IMAGE_HOSTNAME="${RT_IMAGE_HOSTNAME:-motion-master}"

log() { printf '[rt-image] %s\n' "$*"; }
die() {
    printf '[rt-image] error: %s\n' "$*" >&2
    exit 1
}
require() { command -v "$1" >/dev/null 2>&1 || die "'$1' is not installed"; }

require qemu-system-aarch64
require qemu-img
require curl
require xz
require ssh
require ansible-playbook
require openssl

# How the finished card is logged into. Two separate keypairs are in play, and
# conflating them is the mistake to avoid:
#
#   SSH_KEY     throwaway, per-.cache, build-only. Authorised before the QEMU
#               boot so Ansible can get in, and removed again at the end.
#   ACCESS_KEY  durable, and deliberately NOT a secret — this is the key handed
#               to whoever owns a board. Its public half is baked into every
#               image built here.
#
# ACCESS_KEY lives in the invoking user's ~/.ssh, not in the repository: it is an
# SSH key and that is where SSH keys go, whereas a private key inside a git
# working tree is one `git add -A` away from being committed to a public
# repository (whose push protection would likely reject it anyway). Nor does it
# belong in .cache, which is advertised as disposable — deleting that directory
# must never cost you the key that opens every card already in the field.
#
# $HOME is not usable to find it. This script is frequently run under sudo, where
# $HOME is /root, and the key would land somewhere its owner cannot read.
INVOKING_USER="${SUDO_USER:-$(id -un)}"
INVOKING_HOME="$(getent passwd "$INVOKING_USER" | cut -d: -f6)"
[ -n "$INVOKING_HOME" ] || die "could not determine the home directory of $INVOKING_USER"

ACCESS_KEY="${RT_IMAGE_ACCESS_KEY:-$INVOKING_HOME/.ssh/motion-master-rpi}"

# The root password is the account name by default (root/root), which is a
# deliberate choice rather than an oversight: the board's HTTP API is
# unauthenticated and binds every interface, so a login password is not what is
# protecting anything, and console access is what makes a board recoverable on
# the day the network does not come up. Set RT_IMAGE_ROOT_PASSWORD to override,
# or to the empty string to leave the account locked and key-only.
ROOT_PASSWORD="${RT_IMAGE_ROOT_PASSWORD-root}"

# Run this as yourself, not under sudo. Only the loop-mount/chroot block needs
# root; the download, the image resize, the QEMU boot, Ansible and the checks are
# all ordinary user work, and doing them as root just leaves an 8 GB image and a
# private key root-owned in your repository.
#
# The catch that makes a blanket sudo tempting is that the privileged block spans
# a slow emulated apt install, so sudo's timestamp can expire and re-prompt in
# the middle of it. Ask once here instead, and keep the timestamp warm for the
# rest of the run.
if [ "$(id -u)" -ne 0 ]; then
    sudo -v || die "this needs sudo for the loop-mount and chroot steps"
    while true; do
        sudo -n true 2>/dev/null || true
        sleep 50
        kill -0 "$$" 2>/dev/null || exit
    done &
    SUDO_KEEPALIVE=$!
fi

# Only relevant when someone runs the whole script under sudo anyway: hand back
# what would otherwise be left root-owned.
OWNER="${SUDO_USER:-$(id -un)}"
restore_ownership() {
    [ "$OWNER" != "$(id -un)" ] || return 0
    chown -R "$OWNER" "$CACHE_DIR" 2>/dev/null || true
}

cleanup_mounts() {
    for d in dev/pts dev sys proc; do
        sudo umount "$MOUNT_DIR/root/$d" 2>/dev/null || true
    done
    sudo umount "$MOUNT_DIR/boot" 2>/dev/null || true
    sudo umount "$MOUNT_DIR/root" 2>/dev/null || true
    if [ -n "${LOOP_DEV:-}" ]; then
        sudo losetup -d "$LOOP_DEV" 2>/dev/null || true
        LOOP_DEV=""
    fi
}
# QEMU is started with -daemonize, so it outlives this script unless something
# stops it. Interrupting a run would otherwise leave it holding the image file
# open and port 2223 bound, and the next run fails in a way that looks unrelated.
stop_qemu() {
    [ -f "$PID_FILE" ] || return 0
    local pid
    pid=$(cat "$PID_FILE" 2>/dev/null) || return 0
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        kill "$pid" 2>/dev/null || true
        for _ in $(seq 20); do
            kill -0 "$pid" 2>/dev/null || break
            sleep 0.5
        done
        kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$PID_FILE"
}

# Ownership last, and on every exit path — a failed run leaves artifacts too.
cleanup() {
    [ -n "${SUDO_KEEPALIVE:-}" ] && kill "$SUDO_KEEPALIVE" 2>/dev/null
    stop_qemu
    cleanup_mounts
    restore_ownership
}
trap cleanup EXIT

mkdir -p "$CACHE_DIR"

# An earlier run under sudo leaves the image, the keypair and the mount points
# owned by root, which stops the very first cp of an ordinary run. Take them
# back rather than making that someone else's puzzle.
if [ "$(id -u)" -ne 0 ] && find "$CACHE_DIR" -maxdepth 1 ! -user "$(id -un)" -print -quit | grep -q .; then
    log "reclaiming root-owned files from a previous sudo run"
    sudo chown -R "$(id -un)" "$CACHE_DIR"
fi

# ── 1. base image ─────────────────────────────────────────────────────────────

if [ ! -f "$BASE_IMAGE" ]; then
    # Downloaded to a file rather than piped straight into tar. Piping looks
    # tidier — one 3 GB disk.raw instead of that plus a 372 MB tarball — but
    # --retry then restarts a failed transfer from byte 0 and feeds tar the
    # stream twice, which surfaces as "xz: Compressed data is corrupt" after
    # several minutes. With a file, --retry and -C (resume) both work.
    log "downloading $BASE_NAME (~372 MB)"
    curl -fL --retry 5 --retry-delay 2 -C - --progress-bar \
        -o "$CACHE_DIR/$BASE_NAME" "$BASE_URL/$BASE_NAME"

    log "extracting disk.raw (~3 GB)"
    tar -xJf "$CACHE_DIR/$BASE_NAME" -C "$CACHE_DIR" disk.raw
    rm -f "$CACHE_DIR/$BASE_NAME"
fi

log "creating working image ($IMAGE_SIZE)"
cp --reflink=auto "$BASE_IMAGE" "$WORK_IMAGE"
qemu-img resize -f raw "$WORK_IMAGE" "$IMAGE_SIZE" >/dev/null

# Partition numbers come from the GPT type GUIDs. This image is GPT in the
# Debian cloud arrangement — root is partition 1 and the firmware ESP is
# partition 15, the opposite of the p1=boot, p2=root layout a Raspberry Pi image
# is usually assumed to have — so nothing here may assume an ordering.
read -r ESP_NUM ROOT_NUM < <(sfdisk -J "$WORK_IMAGE" 2>/dev/null | python3 -c "
import json, sys
table = json.load(sys.stdin)['partitiontable']
device, esp, root = table['device'], '', ''
for part in table['partitions']:
    number = part['node'].replace(device, '')
    if part.get('type', '').lower() == 'c12a7328-f81f-11d2-ba4b-00a0c93ec93b':
        esp = number
    else:
        root = number
print(esp, root)
")
[ -n "$ESP_NUM" ] && [ -n "$ROOT_NUM" ] ||
    die "could not identify the ESP and root partitions in $BASE_NAME"
log "  partitions: firmware=$ESP_NUM root=$ROOT_NUM"

# Growing the file leaves GPT's backup header stranded mid-disk, and every
# subsequent partition operation refuses with "The backup GPT table is not on
# the end of the device" until it is moved to the new end.
sfdisk --relocate gpt-bak-std "$WORK_IMAGE" >/dev/null 2>&1 ||
    log "  (could not relocate the backup GPT header)"

# Grow the root partition into the space just added. The filesystem inside it is
# resized further down, once the loop device exists.
parted -s "$WORK_IMAGE" resizepart "$ROOT_NUM" 100% 2>/dev/null ||
    log "  (could not grow the root partition — continuing at its original size)"

if [ ! -f "$SSH_KEY" ]; then
    ssh-keygen -t ed25519 -N '' -C motion-master-rpi-image -f "$SSH_KEY" >/dev/null
fi

# Only the public half is needed to build an image; the private half is the thing
# handed to board owners, and a build host has no business needing it. Generating
# a fresh pair whenever the public key is merely missing would be the worst
# outcome available here — the build would succeed and produce a card that the
# key already distributed to owners cannot open — so this writes both halves
# exactly once, and says so loudly enough to be noticed.
if [ ! -f "$ACCESS_KEY.pub" ]; then
    install -d -m 700 -o "$INVOKING_USER" "$(dirname "$ACCESS_KEY")"
    ssh-keygen -t ed25519 -N '' -C motion-master-rpi -f "$ACCESS_KEY" >/dev/null
    # Under sudo ssh-keygen writes root-owned files into someone else's ~/.ssh,
    # where the person who has to use the key cannot read it.
    chown "$INVOKING_USER" "$ACCESS_KEY" "$ACCESS_KEY.pub"
    log ""
    log "NOTE: no access key was found, so a new one has been generated:"
    log "  $ACCESS_KEY      (private — give this to board owners)"
    log "  $ACCESS_KEY.pub  (public  — baked into every image built here)"
    log "Keep both, and back them up. A card built from one key will not accept"
    log "another, so losing these locks you out of every board already flashed."
    log ""
fi

# ── 2. open the image and prepare first boot ─────────────────────────────────
#
# The stock image has no SSH key and a locked root account, and its kernel and
# initrd have to come out to the host because QEMU's "virt" machine cannot boot
# via the Pi firmware.

log "mounting the image"
mkdir -p "$MOUNT_DIR/boot" "$MOUNT_DIR/root"
LOOP_DEV=$(sudo losetup --find --show --partscan "$WORK_IMAGE")

BOOT_PART="${LOOP_DEV}p${ESP_NUM}"
ROOT_PART="${LOOP_DEV}p${ROOT_NUM}"

# --partscan asks the kernel to scan; the device nodes appear via udev a moment
# later, so a check straight after losetup can lose the race.
sudo udevadm settle --timeout=10 2>/dev/null || true
for _ in $(seq 20); do
    [ -b "$BOOT_PART" ] && [ -b "$ROOT_PART" ] && break
    sleep 0.5
done
[ -b "$BOOT_PART" ] && [ -b "$ROOT_PART" ] ||
    die "partition devices did not appear: $BOOT_PART / $ROOT_PART"
log "  firmware: $BOOT_PART   root: $ROOT_PART"

# The image file was grown above; hand the extra space to the root filesystem,
# or installing a kernel plus headers runs it out of space.
sudo resize2fs "$ROOT_PART" >/dev/null 2>&1 || true

sudo mount "$BOOT_PART" "$MOUNT_DIR/boot"
sudo mount "$ROOT_PART" "$MOUNT_DIR/root"

# Versioned filenames (vmlinuz-7.1.3+deb14-arm64), not the unversioned symlinks
# a root filesystem carries — the firmware partition holds copies placed there
# by raspi-firmware. Newest wins if a build ever ships more than one.
log "extracting kernel and initrd for the QEMU boot"
KERNEL_SRC=$(sudo sh -c "ls -1 $MOUNT_DIR/boot/vmlinuz-* 2>/dev/null | sort -V | tail -1")
INITRD_SRC=$(sudo sh -c "ls -1 $MOUNT_DIR/boot/initrd.img-* 2>/dev/null | sort -V | tail -1")
[ -n "$KERNEL_SRC" ] && [ -n "$INITRD_SRC" ] ||
    die "no vmlinuz-*/initrd.img-* on the firmware partition"
sudo cp "$KERNEL_SRC" "$CACHE_DIR/vmlinuz"
sudo cp "$INITRD_SRC" "$CACHE_DIR/initrd.img"
sudo chown "$USER" "$CACHE_DIR/vmlinuz" "$CACHE_DIR/initrd.img"

# The image ships neither cloud-init nor openssh-server (confirmed against the
# build's package manifest), so there is no way in until one is put there. This
# runs apt *inside* the arm64 root filesystem on an x86 host, which works only
# because binfmt_misc hands aarch64 binaries to qemu-user-static — installed by
# tools/install-deps.sh.
log "installing openssh-server into the image (arm64 chroot via binfmt)"
[ -x /usr/bin/qemu-aarch64-static ] || [ -f /proc/sys/fs/binfmt_misc/qemu-aarch64 ] ||
    die "no aarch64 binfmt handler — install qemu-user-static (./tools/install-deps.sh)"

for d in proc sys dev dev/pts; do
    sudo mount --bind "/$d" "$MOUNT_DIR/root/$d"
done

# /etc/resolv.conf in the image is a symlink into /run (systemd-resolved), and
# /run is empty in a mounted image — so it dangles, and cp refuses to write
# through it. Swap in a real file for the duration of the chroot and put the
# symlink back afterwards; leaving a plain file there would break DNS on the
# booted board, where systemd-resolved expects to own it.
RESOLV_CONF="$MOUNT_DIR/root/etc/resolv.conf"
RESOLV_LINK=""
if [ -L "$RESOLV_CONF" ]; then
    RESOLV_LINK=$(readlink "$RESOLV_CONF")
    sudo rm -f "$RESOLV_CONF"
fi
sudo cp /etc/resolv.conf "$RESOLV_CONF"

# LANG is forced to C.UTF-8 rather than inherited. The host's en_US.UTF-8 is not
# generated inside this image, so every perl and apt-listchanges call in the
# chroot warns "Can't set locale" and falls back anyway. C.UTF-8 is built into
# glibc, so it needs no locale generation and is always present.
sudo chroot "$MOUNT_DIR/root" /bin/sh -c '
    export LANG=C.UTF-8 LC_ALL=C.UTF-8 DEBIAN_FRONTEND=noninteractive
    apt-get update -qq && apt-get install -y -qq openssh-server'

if [ -n "$RESOLV_LINK" ]; then
    sudo rm -f "$RESOLV_CONF"
    sudo ln -s "$RESOLV_LINK" "$RESOLV_CONF"
fi

for d in dev/pts dev sys proc; do
    sudo umount "$MOUNT_DIR/root/$d"
done

# The image ships an unpopulated /etc — no locale, timezone or machine-id —
# because it expects cloud-init to fill those in. Without one, systemd-firstboot
# stops the boot and asks for them on the console, and waits forever. Fatal for
# a headless appliance: the card would boot to a prompt nobody can see.
#
# So seed the answers, then mask the unit outright. Seeding alone is not enough
# — firstboot also prompts for a root password when it finds none, and this
# image intentionally has root locked (access is by SSH key).
log "seeding first-boot settings and disabling interactive setup"
# Not silenced with "|| true": a failure here is why a board would come up named
# "localhost" with no locale, and that should be loud, not discovered later.
sudo systemd-firstboot --root="$MOUNT_DIR/root" \
    --locale=C.UTF-8 \
    --timezone=UTC \
    --hostname="$IMAGE_HOSTNAME" \
    --setup-machine-id ||
    die "could not seed first-boot settings into the image"

# --hostname only writes /etc/hostname when the file is absent, and the image
# already ships one, so set it unconditionally — otherwise every board answers
# to whatever the base image was called.
printf '%s\n' "$IMAGE_HOSTNAME" | sudo tee "$MOUNT_DIR/root/etc/hostname" >/dev/null

# Same reasoning for the locale: /etc/default/locale is what Debian's PAM stack
# reads for login sessions, and systemd-firstboot writes /etc/locale.conf only.
printf 'LANG=C.UTF-8\n' | sudo tee "$MOUNT_DIR/root/etc/default/locale" >/dev/null

sudo systemctl --root="$MOUNT_DIR/root" mask systemd-firstboot.service >/dev/null ||
    die "could not mask systemd-firstboot.service"

# Blank the machine ID again. Baking a concrete one in would give every card
# flashed from this image the same identity — and so the same DHCP DUID, which
# collides the moment two of them share a network. Empty means "generate one on
# first boot", the standard arrangement for a golden image; the masked unit above
# is what stops that first boot turning into an interactive prompt.
sudo truncate -s 0 "$MOUNT_DIR/root/etc/machine-id"

log "authorising the build key for root"
sudo install -d -m 700 "$MOUNT_DIR/root/root/.ssh"
sudo cp "$SSH_KEY.pub" "$MOUNT_DIR/root/root/.ssh/authorized_keys"
sudo chmod 600 "$MOUNT_DIR/root/root/.ssh/authorized_keys"

# Root over SSH by key only, and only while the image is being built — the last
# step below removes both this and the key.
sudo install -d "$MOUNT_DIR/root/etc/ssh/sshd_config.d"
sudo tee "$MOUNT_DIR/root/etc/ssh/sshd_config.d/99-image-build.conf" >/dev/null <<'EOF'
PermitRootLogin prohibit-password
EOF

# The root filesystem is found by label on the Pi, but QEMU presents it as a
# plain virtio disk, so give the kernel an explicit root= for this boot only.
ROOT_PARTUUID=$(sudo blkid -s PARTUUID -o value "$ROOT_PART")
[ -n "$ROOT_PARTUUID" ] || die "could not read the root PARTUUID from $ROOT_PART"

cleanup_mounts

# ── 3. provision under emulation ──────────────────────────────────────────────

log "booting the image under QEMU (arm64 TCG — no KVM on an x86 host, so this is slow)"
qemu-system-aarch64 \
    -name motion-master-rpi-image \
    -machine virt \
    -cpu cortex-a76 \
    -smp "$VM_CPUS" \
    -m "$VM_MEMORY_MB" \
    -kernel "$CACHE_DIR/vmlinuz" \
    -initrd "$CACHE_DIR/initrd.img" \
    -append "root=PARTUUID=$ROOT_PARTUUID rw rootwait console=ttyAMA0 systemd.firstboot=off" \
    -drive "if=virtio,format=raw,file=$WORK_IMAGE" \
    -netdev "user,id=net0,hostfwd=tcp:$SSH_HOST:$SSH_PORT-:22" \
    -device virtio-net-pci,netdev=net0 \
    -display none \
    -serial "file:$SERIAL_LOG" \
    -pidfile "$PID_FILE" \
    -daemonize

# BatchMode so a key that no longer works fails immediately instead of dropping
# to an interactive password prompt in the middle of an unattended build.
SSH_OPTS=(-i "$SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          -o LogLevel=ERROR -o BatchMode=yes -p "$SSH_PORT")

log "waiting for SSH (up to ${BOOT_TIMEOUT}s under emulation)"
deadline=$((SECONDS + BOOT_TIMEOUT))
until ssh "${SSH_OPTS[@]}" -o ConnectTimeout=5 -o BatchMode=yes "$VM_USER@$SSH_HOST" true 2>/dev/null; do
    kill -0 "$(cat "$PID_FILE")" 2>/dev/null || die "QEMU exited — see $SERIAL_LOG"
    [ "$SECONDS" -lt "$deadline" ] || die "timed out — see $SERIAL_LOG"
    sleep 5
done

log "provisioning with the same playbook the AAeon board uses"
# Through play-rt.sh, not ansible-playbook directly. Ansible reads ansible.cfg
# from the *current directory* and never from beside the playbook, so invoking
# it with absolute paths from wherever this script was started silently picks up
# /etc/ansible/ansible.cfg instead of ours — losing interpreter_python
# (the "discovered Python interpreter" warning) and, more importantly here,
# pipelining, which costs an extra SSH round-trip per task under emulation.
# play-rt.sh cds into the ansible directory first, exactly as rt/vm does.
#
# rt-verify is skipped on purpose: it asserts on the *running* kernel, and this
# guest is running the stock one handed to QEMU, not the RT kernel being written
# into the image. What the image contains is checked below instead.
"$ANSIBLE_DIR/../play-rt.sh" inventory/rpi-image.yml --skip-tags rt-verify

# Provisioning downloads a kernel, its headers and a compiler, and apt keeps
# every .deb it fetched — around 170 MB serving no purpose on a card that will
# never reinstall those exact versions from cache. Dropped here rather than by a
# role, because it is a property of shipping an image and not of configuring a
# host: a real machine benefits from its cache.
#
# Not fatal. With the image sized as it is this is hygiene, not necessity, and
# failing a two-hour build over an unswept cache would be the wrong trade.
log "dropping the apt cache"
ssh "${SSH_OPTS[@]}" "$VM_USER@$SSH_HOST" 'apt-get clean' ||
    log "  (could not clean the apt cache — continuing)"

# ── 4. check what the image ended up containing ───────────────────────────────
#
# Not a real-time check — nothing here can be, since none of it has run on the
# hardware. This only confirms the pieces are present on the card.

log "checking the image contents"
ssh "${SSH_OPTS[@]}" "$VM_USER@$SSH_HOST" 'bash -s' <<'CHECKS' || die "image checks failed"
set -euo pipefail
fail=0
check() {
    if eval "$2" >/dev/null 2>&1; then
        printf '  ok    %s\n' "$1"
    else
        printf '  FAIL  %s\n' "$1"
        fail=1
    fi
}
check "PREEMPT_RT kernel installed"  "ls /boot/vmlinuz-*-rt-* "
check "RT kernel is the newest"      "test \"\$(linux-version list | linux-version sort --reverse | head -1)\" = \"\$(linux-version list | grep -- -rt- | linux-version sort --reverse | head -1)\""
# The generated config.txt is what the Pi firmware acts on, and getting it wrong
# produces a card that panics on boot with no other clue. Both halves are
# checked: an empty "initramfs" line is exactly what an explicit KERNEL= used to
# emit, and a kernel= naming a non-RT image means version-sort picked the wrong
# one.
check "config.txt boots an RT kernel" "grep -qE '^kernel=vmlinuz-.*-rt-' /boot/firmware/config.txt"
check "config.txt names an initrd"   "grep -qE '^initramfs +initrd\.img-.*-rt-' /boot/firmware/config.txt"
check "isolcpus on the command line" "grep -q isolcpus /boot/firmware/cmdline.txt"
check "nohz_full on the command line" "grep -q nohz_full /boot/firmware/cmdline.txt"
check "rtprio limits installed"      "test -f /etc/security/limits.d/99-realtime.conf"
check "motion-master installed"      "test -x /opt/motion-master/motion-master"
check "motion-master enabled"        "systemctl is-enabled motion-master"
# Only that it is armed. Whether it *works* cannot be tested here: this guest's
# disk is the image itself, so there is by definition no free space past the
# partition, and growpart would correctly report nothing to do. The first real
# exercise is the card's first boot.
check "growroot enabled"             "systemctl is-enabled growroot"
check "growroot tooling present"     "command -v growpart && command -v sgdisk"
check "cpuAffinity configured"       "grep -q '\"cpuAffinity\"' /opt/motion-master/motion-master.jsonc"
check "interactive firstboot masked" "test \"\$(systemctl is-enabled systemd-firstboot.service 2>/dev/null)\" = masked"
check "hostname set"                 "test -s /etc/hostname && ! grep -qx localhost /etc/hostname"
check "locale set"                   "grep -q C.UTF-8 /etc/locale.conf && grep -q C.UTF-8 /etc/default/locale"
exit $fail
CHECKS

# ── 5. close up ───────────────────────────────────────────────────────────────

# The build-only SSH access is NOT revoked here, even though this is the last
# time the guest is used. Doing so needs one more SSH call to power the machine
# down, and that call is the first thing the revocation breaks. It is removed
# offline below instead, which is both correctly ordered and not dependent on
# the guest cooperating.
log "shutting down"
ssh "${SSH_OPTS[@]}" "$VM_USER@$SSH_HOST" 'systemctl poweroff --no-block' || true

# Bounded: an unresponsive guest must not hang the build forever. stop_qemu in
# the cleanup trap is the backstop either way.
shutdown_deadline=$((SECONDS + 300))
while kill -0 "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null; do
    if [ "$SECONDS" -ge "$shutdown_deadline" ]; then
        log "  guest did not power off in time — stopping it"
        stop_qemu
        break
    fi
    sleep 2
done
rm -f "$PID_FILE"

# Everything that must be the *last* write to the image happens here, offline,
# with the guest down:
#
#   * The machine ID cannot be blanked from inside, because an empty
#     /etc/machine-id is precisely the instruction to generate one at boot — the
#     provisioning boot would fill it straight back in. Leaving it set gives
#     every card flashed from this image one identity, and one DHCP DUID.
#   * The build key and its sshd drop-in are removed here rather than over SSH,
#     for the ordering reason above — and the durable access key replaces them,
#     so the swap is a single atomic-looking step with no window in which the
#     image carries both, or neither.
log "finalising the image"
LOOP_DEV=$(sudo losetup --find --show --partscan "$WORK_IMAGE")
sudo udevadm settle --timeout=10 2>/dev/null || true
sudo mount "${LOOP_DEV}p${ROOT_NUM}" "$MOUNT_DIR/root"

sudo truncate -s 0 "$MOUNT_DIR/root/etc/machine-id"
[ ! -s "$MOUNT_DIR/root/etc/machine-id" ] || die "machine ID is not blank"

sudo rm -f "$MOUNT_DIR/root/root/.ssh/authorized_keys" \
    "$MOUNT_DIR/root/etc/ssh/sshd_config.d/99-image-build.conf"

log "installing the access key and root password"
sudo install -d -m 700 "$MOUNT_DIR/root/root/.ssh"
sudo install -m 600 -o root -g root "$ACCESS_KEY.pub" \
    "$MOUNT_DIR/root/root/.ssh/authorized_keys"
sudo grep -qF "$(cut -d' ' -f2 <"$ACCESS_KEY.pub")" \
    "$MOUNT_DIR/root/root/.ssh/authorized_keys" ||
    die "the access key was not installed into the image"

# Root over SSH, permanently this time. "yes" rather than prohibit-password
# because a password is being set and both routes in are wanted; with an empty
# RT_IMAGE_ROOT_PASSWORD the account stays locked and this degrades to key-only
# on its own, since sshd cannot accept a password that does not exist.
sudo install -d "$MOUNT_DIR/root/etc/ssh/sshd_config.d"
sudo tee "$MOUNT_DIR/root/etc/ssh/sshd_config.d/50-motion-master.conf" >/dev/null <<'EOF'
# Motion Master appliance: root login by the distributed motion-master-rpi key,
# and by password on the console. See rt/README.md.
PermitRootLogin yes
EOF

# The password is written straight into /etc/shadow rather than through chpasswd
# in a chroot: the bind mounts this needs were torn down before the QEMU boot,
# and re-establishing /proc and /dev to run one command is more moving parts than
# a hash and a substitution. openssl computes the same SHA-512 crypt hash that
# chpasswd would. The field is replaced wholesale, which also clears the "!" that
# locks the account in the stock image.
if [ -n "$ROOT_PASSWORD" ]; then
    ROOT_HASH=$(openssl passwd -6 "$ROOT_PASSWORD")
    [ -n "$ROOT_HASH" ] || die "could not hash the root password"
    sudo sed -i "s|^root:[^:]*:|root:$ROOT_HASH:|" "$MOUNT_DIR/root/etc/shadow"
    # Read the field back and test its prefix, rather than matching a pattern.
    # A crypt hash both starts and ends with the "$" that a regex reads as an
    # end-of-line anchor, so the obvious grep for "^root:\$6\$" matches nothing
    # however it is quoted — it demands the line stop right after "root:$6".
    # This failed a build against an image whose password had in fact been set
    # perfectly well.
    ROOT_FIELD=$(sudo awk -F: '$1 == "root" { print $2 }' "$MOUNT_DIR/root/etc/shadow")
    # shellcheck disable=SC2016  # '$6$' is the literal SHA-512 crypt prefix,
    # not an expansion — single quotes are the point. Rewriting it to satisfy
    # this check is what produced the bug the comment above describes.
    case "$ROOT_FIELD" in
    '$6$'*) ;;
    *) die "the root password was not set in the image" ;;
    esac
else
    log "  RT_IMAGE_ROOT_PASSWORD is empty — leaving root locked, key-only"
fi

cleanup_mounts

log "image ready: $WORK_IMAGE"
log ""
log "Flash it (CHECK THE DEVICE NAME — this overwrites the target):"
log "  sudo dd if=$WORK_IMAGE of=/dev/sdX bs=4M status=progress conv=fsync"
log ""
log "Logging in — the board answers to '$IMAGE_HOSTNAME':"
log "  over SSH        ssh -i $ACCESS_KEY root@<address>"
if [ -n "$ROOT_PASSWORD" ]; then
    log "  on the console  user 'root', password '$ROOT_PASSWORD'"
else
    log "  on the console  disabled — root is locked, the key above is the only way in"
fi
log ""
log "Neither credential is a secret: the key is meant to be handed to board"
log "owners, and the HTTP API on this board is unauthenticated and listens on"
log "every interface regardless. Put it on a network you trust."
log ""
log "The kernel has never run on real hardware. On first boot, confirm over"
log "serial or HDMI that it comes up and that Ethernet appears."
